### ISSUE TITLE
JsEngine error.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#1063]
When I run transform all t4 template it says the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: MsieJavaScriptEngine.JsRuntimeException: Script threw an exception: TypeError: Unable to get property 'kind' of undefined or null referenceTypeError: Unable to get property 'kind' of undefined or null reference
   at visitNode (Unknown script code:437:17)
   at extractTypes (Unknown script code:470:13)
   at parseTypes (Unknown script code:567:21)
   at Global code (Unknown script code:1:1)
   at MsieJavaScriptEngine.JsRt.Edge.ChakraEdgeJsRtJsEngine.InvokeScript[T](Func`1 func)
   at MsieJavaScriptEngine.JsRt.Edge.ChakraEdgeJsRtJsEngine.Evaluate(String expression)
   at MsieJavaScriptEngine.MsieJsEngine.Evaluate[T](String expression)
   at Microsoft.VisualStudio.TextTemplatingB2D29F168C0EAD804259552204320904DC1E3B5A4B9289DBF87AC7C873E69B69BFFBBDB583A3A235CED44EA9A74B66C347FE76AE24563A5F4AB95C65C10B8BCB.GeneratedTextTransformation.TSTypeLister.List()
   at Microsoft.VisualStudio.TextTemplatingB2D29F168C0EAD804259552204320904DC1E3B5A4B9289DBF87AC7C873E69B69BFFBBDB583A3A235CED44EA9A74B66C347FE76AE24563A5F4AB95C65C10B8BCB.GeneratedTextTransformation.TransformText()	TVLSecurity.Web	D:\Work\Security\TVLSecurity\TVLSecurity.Web\Modules\Common\Imports\ClientTypes\ClientTypes.tt	1	

can anybody help to fix this issue?

**Comment by volkanceylan** [comment]
You probably have added a malformed TS file recently.

**Comment by volkanceylan** [comment]
Did you resolve this @dfaruque ?

**Comment by dfaruque** [comment]
Yap, but don't understand why...

In a aDialog.ts , I added the folloing reference to use Select2Item interface.
/// <reference path="../../../scripts/serenity/serenity.corelib.d.ts" />

Then it was giving the above error.

After removing this reference its working. What's happening there?

**Comment by Estrusco** [comment]
@dfaruque and @volkanceylan  

I had the same problem, and after several tests I realized that (in some cases) you have to write a reference respecting upper and lower case.
For example if I add in \BasicSamples\Dialogs\OtherFormInTab\OtherFormInTabDialog.ts a reference to other ts 

```ts
/// <reference path="../../../Northwind/Order/OrderDialog.ts" />
/// <reference path="../../../northwind/customer/customerdialog.ts" />

namespace Serene.BasicSamples {
   [...]
```

I have the error, but if I wrote


```ts
/// <reference path="../../../Northwind/Order/OrderDialog.ts" />
/// <reference path="../../../Northwind/Customer/CustomerDialog.ts" />

namespace Serene.BasicSamples {
   [...]
```

everything is ok

**Comment by dfaruque** [comment]
@Estrusco Thank you. Very helpful.
