### ISSUE TITLE
"Query affected 0 rows while 1 expected!"

### ISSUE THREAD

**Issue by zeezment** [volkanceylan/Serenity#1115]
Hi,

I added a new column, Attachments, to my database table called Claims. Added the references for Attachments to ClaimsColumns, ClaimsRow and ClaimsForm. This field is of type MultipleFileUploadEditor and saves the filename and original name as a string. Everytime I try to add a new Claim with the newly added Attachments column I get the error:
 "{"Query affected 0 rows while 1 expected!"}"
   at Serenity.Data.SqlHelper.CheckExpectedRows(ExpectedRows expectedRows, Int32 affectedRows) in C:\Repos\Serenity\Serenity.Data\SqlHelpers\SqlHelper.cs:line 142
   at Serenity.Data.SqlHelper.Execute(SqlUpdate query, IDbConnection connection, ExpectedRows expectedRows) in C:\Repos\Serenity\Serenity.Data\SqlHelpers\SqlHelper.cs:line 131
   at Serenity.Services.MultipleImageUploadBehavior.OnAfterSave(ISaveRequestHandler handler) in C:\Repos\Serenity\Serenity.Web\Upload\MultipleImageUploadBehavior.cs:line 197
   at Serenity.Services.SaveRequestHandler`3.AfterSave() in C:\Repos\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 42
   at Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType) in C:\Repos\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 288
   at praxis.Claims.Repositories.ClaimsRepository.Create(IUnitOfWork uow, SaveRequest`1 request) in C:\Users\sindiswa.makiwane\Source\Repository\praxis\praxis\praxis.serenity\praxis.serenity.Web\Modules\Claims\Claims\ClaimsRepository.cs:line 28
   at praxis.Claims.Endpoints.ClaimsController.Create(IUnitOfWork uow, SaveRequest`1 request) in C:\Users\sindiswa.makiwane\Source\Repository\praxis\praxis\praxis.serenity\praxis.serenity.Web\Modules\Claims\Claims\ClaimsEndpoint.cs:line 24
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) in C:\Repos\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs:line 57
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation). 

When stepping through the Code when saving the table row, I see that it calls 
ExecuteNonQuery(connection, query.ToString(), query.Params) in 
public static int Execute(this SqlUpdate query, IDbConnection connection, ExpectedRows expectedRows = ExpectedRows.One)
{
    return CheckExpectedRows(expectedRows, ExecuteNonQuery(connection, query.ToString(), query.Params));
}
 on line 131 in SqlHelper.cs twice instead of once which after the second call sets the affectedrows to 0 instead of 1 and the insert fails. Do you have any idea why it would call that method twice..? 
The attachment field is nullable and when I save a claim without adding an attachment the insert for that row gives no errors. When I manually add data in the table via sql manager it executes just fine.. 

Thanks,
Aziza

**Comment by volkanceylan** [comment]
Your table doesnt have a proper ID i guess

**Comment by volkanceylan** [comment]
E.g. Guid that populates on server

**Comment by zeezment** [comment]
Not sure I understand... Please elaborate...
and thanks for the quick reply!!

**Comment by zeezment** [comment]
Changed the ID generation from newid() to newsequentialid() and it still gets the same issue

**Comment by volkanceylan** [comment]
Set ID in BeforeSave, or use autoincrement column

**Comment by zeezment** [comment]
Thank you!!
