### ISSUE TITLE
[MultipleFileUploadEditor] Empty File Error

### ISSUE THREAD

**Issue by VictorTomaili** [volkanceylan/Serenity#1130]
When try to upload empty file, ImageCheckResult gives this error. I will check it soon as possible. 

```
{
  "Error": {
    "Code": "Exception",
    "Message": "Specified argument was out of the range of valid values.
	Parameter name: ImageCheckResult",
    "Details": "System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
	Parameter name: ImageCheckResult
	   at Serenity.Web.ImageChecker.FormatErrorMessage(ImageCheckResult result)
	   at Serenity.Services.ImageUploadBehavior.CheckUploadedImageAndCreateThumbs(ImageUploadEditorAttribute attr, String& temporaryFile)
	   at Serenity.Services.MultipleImageUploadBehavior.CopyTemporaryFiles(ISaveRequestHandler handler, UploadedFile[] oldFileList, UploadedFile[] newFileList, FilesToDelete filesToDelete)
	   at Serenity.Services.MultipleImageUploadBehavior.OnAfterSave(ISaveRequestHandler handler)
	   at Serenity.Services.SaveRequestHandler`3.AfterSave()
	   at Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType)
	   at lambda_method(Closure , ControllerBase , Object[] )
	   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
	   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
	   at Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
	   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
	   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
	   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()
	   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
	   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()
	   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
	   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)"
  }
}
```

**Comment by volkanceylan** [comment]
MultipleFileUploadEditor requires a custom validation rule for such. As its value is empty array.
