### ISSUE TITLE
SqlException Invalid column name 'UserImage' when logging in

### ISSUE THREAD

**Issue by allema** [volkanceylan/Serenity#1278]
When I create a new project based on Serenity template in Visual Studio, run it and try to login I get following exception:
```
SqlException "Invalid column name 'UserImage'."
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at Serenity.Data.SqlHelper.ExecuteReader(IDbConnection connection, String commandText, IDictionary`2 param) in P:\Sandbox\Serene\Serenity\Serenity.Data\SqlHelpers\SqlHelper.cs:line 668
   at Serenity.Data.SqlHelper.ExecuteReader(IDbConnection connection, SqlQuery query) in P:\Sandbox\Serene\Serenity\Serenity.Data\SqlHelpers\SqlHelper.cs:line 721
   at Serenity.Data.EntitySqlHelper.GetSingle(SqlQuery query, IDbConnection connection) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Extensions\EntitySqlHelper.cs:line 88
   at Serenity.Data.EntityConnectionExtensions.TrySingle[TRow](IDbConnection connection, ICriteria where) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Extensions\EntityConnectionExtensions.cs:line 73
   at Asdf1.Administration.UserRetrieveService.GetFirst(IDbConnection connection, BaseCriteria criteria) in C:\wtf\Asdf1\Asdf1\Asdf1.Web\Modules\Administration\User\Authentication\UserRetrieveService.cs:line 16
   at Asdf1.Administration.UserRetrieveService.<>c__DisplayClass4_0.<ByUsername>b__0() in C:\wtf\Asdf1\Asdf1\Asdf1.Web\Modules\Administration\User\Authentication\UserRetrieveService.cs:line 54
   at Serenity.TwoLevelCache.GetInternal[TItem,TSerialized](String cacheKey, TimeSpan localExpiration, TimeSpan remoteExpiration, String groupKey, Func`1 loader, Func`2 serialize, Func`2 deserialize) in P:\Sandbox\Serene\Serenity\Serenity.Core\Caching\TwoLevelCache.cs:line 248
   at Serenity.TwoLevelCache.Get[TItem](String cacheKey, TimeSpan localExpiration, TimeSpan remoteExpiration, String groupKey, Func`1 loader) in P:\Sandbox\Serene\Serenity\Serenity.Core\Caching\TwoLevelCache.cs:line 45
   at Asdf1.Administration.UserRetrieveService.ByUsername(String username) in C:\wtf\Asdf1\Asdf1\Asdf1.Web\Modules\Administration\User\Authentication\UserRetrieveService.cs:line 50
   at Asdf1.Administration.AuthenticationService.Validate(String& username, String password) in C:\wtf\Asdf1\Asdf1\Asdf1.Web\Modules\Administration\User\Authentication\AuthenticationService.cs:line 19
   at Serenity.WebSecurityHelper.Authenticate(String& username, String password, Boolean persist) in P:\Sandbox\Serene\Serenity\Serenity.Web\Security\WebSecurityHelper.cs:line 38
   at Asdf1.Membership.Pages.AccountController.<>c__DisplayClass10_0.<Login>b__0() in C:\wtf\Asdf1\Asdf1\Asdf1.Web\Modules\Membership\Account\AccountPage.cs:line 33
   at Serenity.Services.EndpointExtensions.ExecuteMethod[TResponse](Controller controller, Func`1 handler) in P:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\EndpointExtensions.cs:line 53
```

I'll provide more information if needed.

I'm using Visual Studio 2015 up to date, Windows 10, SQL Express 2016.

**Comment by volkanceylan** [comment]
There was a missing migration file in 2.4.10.2. Either add a UserImage nvarchar(100) column to User table or download 2.4.10.3.

**Comment by allema** [comment]
Thank you, fixed it :)
