### ISSUE TITLE
Custom editor for multiple selection

### ISSUE THREAD

**Issue by jsbUSMC** [volkanceylan/Serenity#130]
Good Evening @volkanceylan I need a bit of guidance about an issue I'm having. I created a custom editor class for multiple selection dropdowns in my project. I also added a partial to the `ScriptEditorTypes.cs` that defines the custom editor attribute. After rebuilding the project and running it, the custom editor appeared just fine in my form, but when I attempted to save the form to test it out I received a ValidationError. Here is the stack trace:

```
Serenity.Services.ValidationError was unhandled by user code
  Arguments=AccessLevel
  ErrorCode=Required
  HResult=-2146233088
  Message=Access Level field is required!
  Source=Serenity.Services
  StackTrace:
       at Serenity.Services.DataValidation.ValidateRequired(Row row, Field field) in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\IntegratedFeatures\Validation\DataValidation.cs:line 67
       at Serenity.Services.DataValidation.ValidateRequired(Row row, IEnumerable`1 fields) in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\IntegratedFeatures\Validation\DataValidation.cs:line 72
       at Serenity.Services.SaveRequestHandler`3.ValidateRequired(HashSet`1 editableFields) in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 394
       at Serenity.Services.SaveRequestHandler`3.ValidateRequest() in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 401
       at Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType) in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 281
       at FlowState.Operations.Repositories.AccessListRepository.Create(IUnitOfWork uow, SaveRequest`1 request) in C:\Users\jbissonette\Documents\Visual Studio 2015\Projects\FlowState\FlowState\FlowState.Web\Modules\Operations

\AccessList\AccessListRepository.cs:line 18
       at FlowState.Operations.Endpoints.AccessListController.Create(IUnitOfWork uow, SaveRequest`1 request) in C:\Users\jbissonette\Documents\Visual Studio 2015\Projects\FlowState\FlowState\FlowState.Web\Modules\Operations\AccessList

\AccessListEndpoint.cs:line 19
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) in P:\Sandbox\Serene\Serenity\Serenity.Web\Mvc

\ServiceEndpoint.cs:line 57
       at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
  InnerException: 
```

The way I understand it, there's an issue with the savehandler in the endpoint class and the repository class. Is this because I have defined my fields as accepting an `Int32` instead of a `List<Row>`? Any help would be greatly appreciated. Here is the code, some parts are left off for brevity sake:

```c#
// Custom editor class
namespace FlowState.Operations
{
    using jQueryApi;
    using Serenity;

    public class AccessLevelEditor : LookupEditorBase<AccessLevelRow>
    {
        public AccessLevelEditor(jQueryObject container, LookupEditorOptions options)
            : base(container, options)
        {
        }

        protected override Select2Options GetSelect2Options()
        {
            var opts = base.GetSelect2Options();
            opts.Multiple = true;

            return opts;
        }

        protected override string GetLookupKey()
        {
            return AccessLevelRow.LookupKey;
        }

        protected override string GetItemText(AccessLevelRow item, Lookup<AcccessLevelRow> lookup)
        {
            return base.GetItemText(item, lookup);
        }
    }
}


// Partial class for the attribute
namespace FlowState.Operations
{
    public partial class AccessLevelEditorAttribute : CustomEditorAttribute
    {
        public const string Key = "FlowState.Operations.AccessLevelEditor";

        public AccessLevelEditorAttribute()
            : base(Key)
        {
        }
    }
}


// Here where I implement the editor in my AccessListRow, which has the AccessLevelEditor to select multiple Access Levels to assign to a user
        [DisplayName("Access Level"), NotNull, ForeignKey("[ops].[AccessLevel]", "AccessLevelId"), LeftJoin("jAccessLevel"), TextualField("AccessLevelAccessLevelDesc")]
        [AccessLevelEditor]
        public Int32? AccessLevel
        {
            get { return Fields.AccessLevel[this]; }
            set { Fields.AccessLevel[this] = value; }
        }

```

Once again, thank you for all your help and guidance!

**Comment by volkanceylan** [comment]
I'll add a sample for multi-select. When Select2 is in multi select mode, it returns an array as value, thats why you get that error. Anyway, on server side, how are you gonna store multiple access levels in one Int32 field?

Till i do it, i recommend you use master/detail style editing, or wait a bit more.

**Comment by volkanceylan** [comment]
Hi again, see CustomerRow Representatives sample in 1.9.3 template. You need a linking table for it to work. If you only want to keep a comma separated list in string field, instead of linking table, set Delimited to true of LookupEditor.

**Comment by jsbUSMC** [comment]
Thank you for your help and all your hard work. I'll get that going right now, and if I have any specific issues then I'll open a new issue.
