### ISSUE TITLE
my database for log in 

### ISSUE THREAD

**Issue by satsokn** [volkanceylan/Serenity#1477]
i tried to connect my existing database to get user details to  login.  I created all the necessary fields as UserId Username Passwordhash Passwoardsalt  IsActive in my Database. I changed connection string and all the default fileds refering to localdatabase being created from migrations (DefaultDB). When i try to run i am getting an exception (inside SiteInitialization.cs in line Serenity.Web.CommonInitialization.Run();)  Exception has been thrown by the target of an invocation. 
Any suggestions?

**Comment by volkanceylan** [comment]
Debug it and check details

**Comment by satsokn** [comment]
System.Reflection.TargetInvocationException was unhandled by user code
  HResult=-2146232828
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
       at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
       at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
       at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
       at System.Activator.CreateInstance(Type type, Boolean nonPublic)
       at System.Activator.CreateInstance(Type type)
       at Serenity.Data.RowRegistry.Initialize() in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Row\RowRegistry.cs:line 113
       at Serenity.Data.RowRegistry.EnsureRegistry() in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Row\RowRegistry.cs:line 98
       at Serenity.Data.RowRegistry.<EnumerateRows>d__8.MoveNext() in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Row\RowRegistry.cs:line 0
       at Serenity.Localization.EntityLocalTexts.Initialize(String languageID) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Extensions\EntityLocalTexts.cs:line 18
       at Serenity.Web.CommonInitialization.InitializeLocalTexts() in P:\Sandbox\Serene\Serenity\Serenity.Web\Common\CommonInitialization.cs:line 102
       at Serenity.Web.CommonInitialization.Run() in P:\Sandbox\Serene\Serenity\Serenity.Web\Common\CommonInitialization.cs:line 24
       at Serene.SiteInitialization.ApplicationStart() in C:\Users\knomikos\Desktop\name change - Copy\Serene\Serene.Web\App_Start\SiteInitialization.cs:line 37
       at Serene.Global.Application_Start(Object sender, EventArgs e) in C:\Users\knomikos\Desktop\name change - Copy\Serene\Serene.Web\Global.asax.cs:line 26
  InnerException: 
       HResult=-2146233036
       Message=The type initializer for 'Serene.Administration.Entities.UserRow' threw an exception.
       Source=Serene.Web
       TypeName=Serene.Administration.Entities.UserRow
       StackTrace:
            at Serene.Administration.Entities.UserRow..ctor()
       InnerException: 
            HResult=-2146233030
            Message=Field UPGINUSERIDD in type UserRow is null and has no corresponding property in entity!
            Source=Serenity.Data.Entity
            StackTrace:
                 at Serenity.Data.RowFieldsBase.Initialize() in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Row\RowFieldsBase.cs:line 266
                 at Serenity.Data.RowExtensions.Init[TRowFields](TRowFields rowFields) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Extensions\RowExtensions.cs:line 46
                 at Serene.Administration.Entities.UserRow..cctor() in C:\Users\knomikos\Desktop\name change - Copy\Serene\Serene.Web\Modules\Administration\User\UserRow.cs:line 117
            InnerException: 




these are the details of the error that occurs. 
the UPGINUSERIDD is  same column as UserId in the turorial(int, not null).
Furthermore when i use breakpoint inside UserRow i dont get any break. The error occurs inside SiteInitialization.cs in line Serenity.Web.CommonInitialization.Run(); which i can't read.
