### ISSUE TITLE
Permission: System.Reflection.AmbiguousMatchException

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#1554]
Dear guys,
today I've deployed in a test environment and I got this exception:

     System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
       at System.DefaultBinder.SelectProperty(BindingFlags bindingAttr, PropertyInfo[] match, Type returnType, Type[] indexes, ParameterModifier[] modifiers)
       at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
       at System.Type.GetProperty(String name, BindingFlags bindingAttr, Type returnType)
       at System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit)
       at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
       at eService.Administration.Repositories.UserPermissionRepository.ProcessAttributes[TAttr](HashSet`1 hash, MemberInfo member, Func`2 getPermission) in C:\...\Modules\Administration\UserPermission\UserPermissionRepository.cs:line 177
       at eService.Administration.Repositories.UserPermissionRepository.<ListPermissionKeys>b__10_0() in C:\...\Modules\Administration\UserPermission\UserPermissionRepository.cs:line 210
       at Serenity.LocalCache.Get[TItem](String cacheKey, TimeSpan expiration, Func`1 loader) in P:\Sandbox\Serene\Serenity\Serenity.Core\Caching\LocalCache.cs:line 57
       at eService.Administration.Endpoints.UserController.<>c.<GetUserData>b__8_0() in C:\...\Modules\Administration\User\UserEndpoint.cs:line 96
       at Serenity.TwoLevelCache.GetInternal[TItem,TSerialized](String cacheKey, TimeSpan localExpiration, TimeSpan remoteExpiration, String groupKey, Func`1 loader, Func`2 serialize, Func`2 deserialize) in P:\Sandbox\Serene\Serenity\Serenity.Core\Caching\TwoLevelCache.cs:line 248
       at Serenity.TwoLevelCache.GetLocalStoreOnly[TItem](String cacheKey, TimeSpan localExpiration, String groupKey, Func`1 loader) in P:\Sandbox\Serene\Serenity\Serenity.Core\Caching\TwoLevelCache.cs:line 142
       at eService.Administration.Endpoints.UserController.GetUserData() in C:\...\Modules\Administration\User\UserEndpoint.cs:line 116
       --- End of inner exception stack trace ---
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Serenity.Web.DynamicScriptRegistration.<>c__DisplayClass0_1.<Initialize>b__2() in P:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\PropertyEditor\DynamicScriptRegistration.cs:line 97
       at Serenity.Web.DataScript.GetScript() in P:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScriptTypes\DataScript.cs:line 27
       at Serenity.Web.DynamicScriptManager.Item.GenerateContent() in P:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScript\DynamicScriptManager.Item.cs:line 79
       at Serenity.Web.DynamicScriptManager.GetScript(String name) in P:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScript\DynamicScriptManager.cs:line 95
       at Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessScriptRequest(HttpContext context, String scriptKey, String contentType) in P:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScript\DynamicScriptHandler.cs:line 21
       at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
       at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

strange thing is that on dev environment everything is working fine...
Someone else has experienced the same problem/issue/exception?
I'm fighting with this one since this morning, but I have no idea on what could be the problem, because I'm not able to replicated it on dev...
I think that is something related to the (new?) permission system, but honestly I don't know...

Thanks for your feedbacks4
Bye

**Comment by marcobisio** [comment]
Just an update: I tried to rollback all the code related to the new permission system (UserPermissionRepository, SiteInitialization, etc.) and the error is gone...still digging!

**Comment by volkanceylan** [comment]
You have a strange production system @marcobisio 
Better delete apps and start from stratch. I strongly suspect you have a misconfiguration.

**Comment by marcobisio** [comment]
I've the same feeling, but on the paper is everything ok...the script bundler first and this one now...they have something in common? 
There is some specific IIS setting that Serenity needs? 
It's very hard to debug this "thing", also because on my laptop with Visual Studio 2015 and SS2008R2 everything it's working fine... :-/

**Comment by volkanceylan** [comment]
You might have such tree:

IIS Site <= some app, or Serenity App
        Subfolder <= Serenity App

This would break all. Also try clearing bin folder and ASP.NET temporary files.

**Comment by marcobisio** [comment]
I'll try!
Thanks
