### ISSUE TITLE
datetime2 error in sql server 2005

### ISSUE THREAD

**Issue by gjw152** [volkanceylan/Serenity#1739]
I am facing error when trying to create a new user:
`System.ArgumentException: The version of SQL Server in use does not support datatype 'datetime2'.
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Serenity.Data.SqlHelper.ExecuteReader(IDbConnection connection, String commandText, IDictionary`2 param)
   at Serenity.Data.SqlHelper.ExecuteAndGetID(SqlInsert query, IDbConnection connection)
   at Serenity.Services.SaveRequestHandler`3.ExecuteSave()
   at Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType)
   at BackOffice.Administration.Endpoints.UserController.<>c__DisplayClass0_0.<Create>b__0(IUnitOfWork uow)
   at Serenity.Services.EndpointExtensions.InTransaction[TResponse](Controller controller, String connectionKey, Func`2 handler)`

**Comment by volkanceylan** [comment]
Have a look at guide for dialects
