### ISSUE TITLE
Accessing data from webservice

### ISSUE THREAD

**Issue by c9482** [volkanceylan/Serenity#1887]
Hello Volkan,

I have a webservice page in my Serenity project with the following method:

```
        [WebMethod]
        [XmlInclude(typeof(LicenseType))]
        public ArrayList GetLicenseTypes()
        {
           // This does not work
            /*string username = "admin";
            if (WebSecurityHelper.Authenticate(ref username, "serenity", true))
            {
                throw new Exception("Authentication error");
            }*/

            ArrayList result = new ArrayList();
            ListRequest request = new ListRequest();
            IDbConnection connection = SqlConnections.NewByKey("Default");
            ListResponse<LicenseTypeRow> licenseTypes = new MyLicenseTypeRepository().List(connection, request);
            foreach (LicenseTypeRow cr in licenseTypes.Entities)
            {
                LicenseType c = new LicenseType();
                c.LicenseTypeId = cr.LicenseTypeId.Value;
                c.LicenseTypeName = cr.LicenseTypeName;
                if (cr.UpdateDate != null) c.UpdateDate = cr.UpdateDate.Value;
                c.UpdateUser = cr.UpdateUser;
                if (cr.InsertDate != null) c.InsertDate = cr.InsertDate.Value;
                c.InsertUser = cr.InsertUser;

                result.Add(c);
            }

            return result;

        }

```
I can access the page only when I am logged in to the web app. When I am logged out, it does not work. How do I get around this error:

Serenity.Services.ValidationError: Authorization has been denied for this request!
   at Serenity.Authorization.ValidatePermission(String permission) in C:\Sandbox\Serene\Serenity\Serenity.Core\Authorization\Authorization.cs:line 108
   at Serenity.Services.ListRequestHandler`3.ValidatePermissions() in C:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\List\ListRequestHandler.cs:line 441
   at Serenity.Services.ListRequestHandler`3.ValidateRequest() in C:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\List\ListRequestHandler.cs:line 446
   at Serenity.Services.ListRequestHandler`3.Process(IDbConnection connection, TListRequest request) in C:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\List\ListRequestHandler.cs:line 501
   at LCPermits.Default.Repositories.LicenseTypeRepository.List(IDbConnection connection, ListRequest request) in C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\Modules\Default\LicenseType\LicenseTypeRepository.cs:line 38
   at LCPermits.WebService.GetLicenseTypes() in C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\WebService.asmx.cs:line 41

**Comment by volkanceylan** [comment]
When you change a cookie, you don't set it for current request but subsequent requests.

You need to use ImpersonatingAuthenticationService like 

https://github.com/volkanceylan/Serenity/issues/564

**Comment by c9482** [comment]
I added this in ApplicationStart():

`registrar.RegisterInstance(new ImpersonatingAuthorizationService(new AuthorizationService()));`

My webservice method is as follows:

```
        [WebMethod]
        [XmlInclude(typeof(LicenseType))]
        public ArrayList GetLicenseTypes()
        {
            Dependency.Resolve<ImpersonatingAuthorizationService>().Impersonate("admin");

            ArrayList result = new ArrayList();
            ListRequest request = new ListRequest();
            IDbConnection connection = SqlConnections.NewByKey("Default");
            ListResponse<LicenseTypeRow> licenseTypes = new MyLicenseTypeRepository().List(connection, request);
            foreach (LicenseTypeRow cr in licenseTypes.Entities)
            {
                LicenseType c = new LicenseType();
                c.LicenseTypeId = cr.LicenseTypeId.Value;
                c.LicenseTypeName = cr.LicenseTypeName;
                if (cr.UpdateDate != null) c.UpdateDate = cr.UpdateDate.Value;
                c.UpdateUser = cr.UpdateUser;
                if (cr.InsertDate != null) c.InsertDate = cr.InsertDate.Value;
                c.InsertUser = cr.InsertUser;

                result.Add(c);
            }
            
            Dependency.Resolve<ImpersonatingAuthorizationService>().UndoImpersonate();

            return result;

        }

```Still getting error:

Serenity.Services.ValidationError: Authorization has been denied for this request!
   at Serenity.Authorization.ValidatePermission(String permission) in C:\Sandbox\Serene\Serenity\Serenity.Core\Authorization\Authorization.cs:line 108
   at Serenity.Services.ListRequestHandler`3.ValidatePermissions() in C:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\List\ListRequestHandler.cs:line 441
   at Serenity.Services.ListRequestHandler`3.ValidateRequest() in C:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\List\ListRequestHandler.cs:line 446
   at Serenity.Services.ListRequestHandler`3.Process(IDbConnection connection, TListRequest request) in C:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\List\ListRequestHandler.cs:line 501
   at LCPermits.Default.Repositories.LicenseTypeRepository.List(IDbConnection connection, ListRequest request) in C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\Modules\Default\LicenseType\LicenseTypeRepository.cs:line 38
   at LCPermits.WebService.GetLicenseTypes() in C:\ngs-projects\LCPermitsProduct\LCPermits\LCPermits\LCPermits.Web\WebService.asmx.cs:line 38

**Comment by volkanceylan** [comment]
You miss important steps. @samdubey recently added a wiki entry about sending mails, it should be helpful.

**Comment by Dinesteine** [comment]
hi c9482

Please check the permission for LicenseTypeRow. You should give read permission to anonymous user in LicenseTypeRow.

Regards,
Dinesteine

**Comment by c9482** [comment]
I made work with ImpersonatingAuthorizationService. How do you create anonymous user?
