### ISSUE TITLE
Authorization.hasPermission() exception

### ISSUE THREAD

**Issue by quidrick** [volkanceylan/Serenity#2070]
Client side Authorization.hasPermission() throws exception if user doesn't have "User, Role Management and Permissions" granted. 
```
Serenity.Services.ValidationError: Authorization has been denied for this request!
   at Serenity.Authorization.ValidatePermission(String permission) in C:\Sandbox\Serene\Serenity\Serenity.Core\Authorization\Authorization.cs:line 108
   at Serenity.Web.DynamicScript.CheckRights() in C:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScriptTypes\DynamicScript.cs:line 23
   at Serenity.Web.DynamicScriptManager.GetScript(String name) in C:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScript\DynamicScriptManager.cs:line 94
   at Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessScriptRequest(HttpContext context, String scriptKey, String contentType) in C:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScript\DynamicScriptHandler.cs:line 18
   at Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessRequest(HttpContext context) in C:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScript\DynamicScriptHandler.cs:line 58
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

Steps to reproduce: 
1. Create new project with latest Serene template
2. Add following to Modules/Northwind/Customer/CustomerDialog.ts
```
protected updateInterface(): void {
    super.updateInterface();
    if (!(Authorization.hasPermission("Northwind:Customer:Modify"))) {
            this.deleteButton.hide();
            this.saveAndCloseButton.hide();
            this.applyChangesButton.hide();
            Serenity.EditorUtils.setReadonly(this.element.find('.editor'), true);
    }
}
```

3. Add user without "User, Role Management and Permissions" permission, login to that user and try to edit any Northwind Customer

**Comment by quidrick** [comment]
Thank you. That works.
