### ISSUE TITLE
Debug with VS2017 error map file not found

### ISSUE THREAD

**Issue by rogerfillion** [volkanceylan/Serenity#2098]
I use last version 2.9.21 with Serenity project, and I can't debug a typescript. VS2017 can't attach to IE.

I have this error in output windows:

'iexplore.exe' (Script) : Chargé 'Code de script (Windows Internet Explorer)'. 
System.Web.HttpException (0x80004005): File not found!
   at Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessScriptRequest(HttpContext context, String scriptKey, String contentType) in P:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScript\DynamicScriptHandler.cs:line 23
   at Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessRequest(HttpContext context) in P:\Sandbox\Serene\Serenity\Serenity.Web\DynamicScript\DynamicScript\DynamicScriptHandler.cs:line 58
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
Configuration invalid: ToAddress must have a value
SourceMap http://localhost:52151/DynJS.axd/toastr.js.map read failed: Une ou plusieurs erreurs se sont produites..'iexplore.exe' (Script) : Chargé 'Sourcemap (http://localhost:52151/Scripts/vegas/vegas.min.js)'.

**Comment by rogerfillion** [comment]
When I use a version 2.8, debug on Vs2017 works. The upgrade to 2.9 broke this function.

**Comment by volkanceylan** [comment]
There is no such change

**Comment by volkanceylan** [comment]
Script bundling might be the issue. Try disabling it.

**Comment by rogerfillion** [comment]
Yes, when I disabling Script bundling in web.config, the debug on Chrome work.

Thanks
