### ISSUE TITLE
Linux Error, dotnet run 

### ISSUE THREAD

**Issue by bensonokiora** [volkanceylan/Serenity#2161]
EXEC : warning : Cannot find module './typescriptServices.js' [/var/www/Project/Project.Web/Project.Web.csproj]
/var/www/Project/Project.Web/Project.Web.csproj(43,5): warning MSB3073: The command "dotnet sergen clienttypes" exited with code 134.

Project.Web.csproj(44,5): error MSB3073: The command "cmd /c "npm" install" exited with code 127.

**Comment by volkanceylan** [comment]
Find this line in your csproj

`<Exec Command="cmd /c &quot;$(NpmPath)npm&quot; install" />`

Replace with 

`<Exec Command="npm install" />`

Make sure you install all prerequisites

**Comment by bensonokiora** [comment]
`<Exec Command="npm install" />`

Now works , but am still getting the errors below
```

EXEC : warning : Cannot find module './typescriptServices.js' [/var/www/Project/Project.Web/Project.Web.csproj]
/var/www/Project/Project.Web/Project.Web.csproj(43,5): warning MSB3073: The command "dotnet sergen clienttypes" exited with code 134.
Modules/Meeting/MeetingAttendee/MeetingAttendeeEditor.ts(1,1): warning TS6053: File '/var/www/Project/Project.Web/Modules/common/helpers/grideditorbase.ts' not found. [/var/www/Project/Project.Web/Project.Web.csproj]
/var/www/Project/Project.Web/Project.Web.csproj(48,5): warning MSB3073: The command "node_modules/.bin/tsc -p ./tsconfig.json" exited with code 2.
EXEC : warning : Cannot find module './typescriptServices.js' [/var/www/Project/Project.Web/Project.Web.csproj]
/var/www/Project/Project.Web/Project.Web.csproj(49,5): warning MSB3073: The command "dotnet sergen servertypings" exited with code 134.

```

**Comment by volkanceylan** [comment]
Did you publish project to www ???

**Comment by bensonokiora** [comment]
I installed a clean Version of LAMP Ubuntu 14.0.4 on DigitalOcean, (apache-as-a-reverse-proxy),
 Installed dotnet 1.0.1, node 6.10.2 (LTS) npm 3.10.10 , typescript@2.1.5, and serin -g 
and created a new project(SereneTest)

The .Net Core version works well on My windows Machine

but am still getting the errors below on Linux even during publishing. Any further assistance Please?
```
root@itaxDashboard:/var/www/html/SereneTest.Web# dotnet publish
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Transforming MVC at: /var/www/html/SereneTest.Web/Imports/MVC
  module.js:471
      throw err;
      ^

EXEC : warning : Cannot find module './typescriptServices.js' [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
      at Function.Module._resolveFilename (module.js:469:15)
      at Function.Module._load (module.js:417:25)
      at Module.require (module.js:497:17)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (/tmp/tmp0Nh70g__/index.js:2:13)
      at Module._compile (module.js:570:32)
      at Object.Module._extensions..js (module.js:579:10)
      at Module.load (module.js:487:32)
      at tryModuleLoad (module.js:446:12)
      at Function.Module._load (module.js:438:3)

  Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/tmp/tmp0Nh70g__/typeList.json'.
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
     at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
     at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
     at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.File.InternalReadAllText(String path, Encoding encoding)
     at System.IO.File.ReadAllText(String path)
     at Serenity.CodeGenerator.TSTypeLister.List()
     at Serenity.CodeGenerator.Program.<>c__DisplayClass0_0.<Main>b__1()
     at Serenity.CodeGenerator.Program.Main(String[] args)
/var/www/html/SereneTest.Web/SereneTest.Web.csproj(43,5): warning MSB3073: The command "dotnet sergen clienttypes" exited with code 134.
  SereneTest.Web -> /var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/SereneTest.Web.dll
Modules/Meeting/MeetingAttendee/MeetingAttendeeEditor.ts(1,1): warning TS6053: File '/var/www/html/SereneTest.Web/Modules/common/helpers/grideditorbase.ts' not found. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/var/www/html/SereneTest.Web/SereneTest.Web.csproj(48,5): warning MSB3073: The command "node_modules/.bin/tsc -p ./tsconfig.json" exited with code 2.
  module.js:471
      throw err;
      ^

EXEC : warning : Cannot find module './typescriptServices.js' [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
      at Function.Module._resolveFilename (module.js:469:15)
      at Function.Module._load (module.js:417:25)
      at Module.require (module.js:497:17)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (/tmp/tmpknsUy8__/index.js:2:13)
      at Module._compile (module.js:570:32)
      at Object.Module._extensions..js (module.js:579:10)
      at Module.load (module.js:487:32)
      at tryModuleLoad (module.js:446:12)
      at Function.Module._load (module.js:438:3)

  Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/tmp/tmpknsUy8__/typeList.json'.
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
     at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
     at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
     at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.File.InternalReadAllText(String path, Encoding encoding)
     at System.IO.File.ReadAllText(String path)
     at Serenity.CodeGenerator.TSTypeLister.List()
     at Serenity.CodeGenerator.Program.<>c__DisplayClass0_0.<Main>b__1()
     at Serenity.CodeGenerator.Program.Main(String[] args)
/var/www/html/SereneTest.Web/SereneTest.Web.csproj(49,5): warning MSB3073: The command "dotnet sergen servertypings" exited with code 134.
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 1 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 2 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 3 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 4 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 5 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 6 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 7 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 8 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 9 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 10 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): error MSB3027: Could not copy "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Exceeded retry count of 10. Failed. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): error MSB3021: Unable to copy file "/var/www/html/SereneTest.Web/wwwroot/content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 1 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 2 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 3 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 4 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 5 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 6 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 7 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 8 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 9 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): warning MSB3026: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Beginning retry 10 in 1000ms. Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): error MSB3027: Could not copy "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Exceeded retry count of 10. Failed. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): error MSB3021: Unable to copy file "/var/www/html/SereneTest.Web/wwwroot/Content/site/site.css" to "bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css". Could not find a part of the path '/var/www/html/SereneTest.Web/bin/Debug/netcoreapp1.1/publish/wwwroot/content/site/site.css'. [/var/www/html/SereneTest.Web/SereneTest.Web.csproj]

```
