### ISSUE TITLE
CORE Beta: Error adding first contact 

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2205]
My first time using Serenity. Excellent project !!! 

I tried the Serenity v2.9.21 ASP.NET CORE Beta on VS2017CE with all latest updates. It built fine and ran on my Win10 PC. I added an organization, then added another organization reporting to the first org. Then I added a contact, then received this error: 

FILE: ContactRepository.cs
CODE LINE 16:  return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
EXCEPTION MESSAGE: 
System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'Serenity.ComponentModel.EmailEditorAttribute' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Serenity.ComponentModel.EmailEditorAttribute.Validate(IValidationContext context)
   at Serenity.Services.SaveRequestHandler`3.ValidateFieldValues()
   at Serenity.Services.SaveRequestHandler`3.ValidateRequest()
   at Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType)
   at POC4.Organization.Repositories.ContactRepository.Create(IUnitOfWork uow, SaveRequest`1 request) in C:\Users\Brian\documents\visual studio 2017\Projects\POC4\POC4\POC4.Web\Modules\Organization\Contact\ContactRepository.cs:line 16
   at POC4.Organization.Endpoints.ContactController.Create(IUnitOfWork uow, SaveRequest`1 request) in C:\Users\Brian\documents\visual studio 2017\Projects\POC4\POC4\POC4.Web\Modules\Organization\Contact\ContactEndpoint.cs:line 18
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()

Inner Exception 1:
ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

**Comment by volkanceylan** [comment]
Another meeting module issue, ok lets keep them open.

**Comment by volkanceylan** [comment]
Will be handled in StartSharp
