### ISSUE TITLE
Is MultipleImageUploadEditorAttribute file missing?

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#25]
I want to use MultipleImageUploadEditor attribute but visual studio can not find related attribute file. There are  ImageUploadEditor.cs and ImageUploadEditorAttrbute classes but there is only MultipleImageUploadEditor.cs. Is there anyway to use MultipleImageUploadEditor?

**Comment by volkanceylan** [comment]
Actually you can use it with `EditorType("MultipleImageUpload")`, as editor type attributes are just intellisense helpers. But i'm not sure if multiple upload editor works properly, didn't use it for long time, need to have a look.

**Comment by ademc** [comment]
I tried EditorType attribute usage, editor shown properly but when updating record have an errror:

An exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Serenity.Data.Entity.dll but was not handled in user code

Additional information: Unexpected token when deserializing row: StartArray

Newtonsoft.Json.JsonSerializationException was unhandled by user code
  HResult=-2146233088
  Message=Unexpected token when deserializing row: StartArray
  Source=Serenity.Data.Entity
  StackTrace:
       at Serenity.Data.Field.JsonUnexpectedToken(JsonReader reader) in c:\project\Serenity\Serenity.Data.Entity\FieldTypes\Field.cs:line 132
       at Serenity.Data.StringField.ValueFromJson(JsonReader reader, Row row, JsonSerializer serializer) in c:\project\Serenity\Serenity.Data.Entity\FieldTypes\StringField.cs:line 83
       at Serenity.Data.JsonRowConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in c:\project\Serenity\Serenity.Data.Entity\Row\JsonRowConverter.cs:line 109
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
  InnerException:

**Comment by volkanceylan** [comment]
Error you are getting is because MultipleImageUploadEditor sends JSON array to server side by default as field value, and it can't be deserialized to a string field.

Please update Serenity nuget packages to 1.5.1.

I tried making sure MultipleImageUpload works properly in this version.

Then use the ImageUploadEditor attribute like below:

```cs
        [ImageUploadEditor(allowMultiple: true, JsonEncodeValue = true)]
        public String ProductImages { get; set; }
```

And on top of your SaveHandler you should use EmbeddedMultiFileUploadBehaviour instead of EmbeddedFileUploadBehaviour as below:

```cs
[EmbeddedMultiFileUploadBehaviour("SonHareketAciklama", fileNameFormat: "ProductImage/{1:00000}/{0:00000000}_{2}", copyFilesToHistory: true)]
private class MySaveHandler : SaveRequestHandler<MyRow> {
}
```

After this it should work.

**Comment by zehranur** [comment]
I updated serenity packages. I can use ImageUploadEditor . There is no EmbeddedMultiFileUploadBehaviour attribute class. I used EmbeddedFileUploadBehaviour and normally get an error:

Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-2.1.4.js?v=EH--lVW_yI7FyrUkx5D-NA2:8630 POST http://localhost:59837/File/TemporaryUpload 404 (Not Found)

**Comment by volkanceylan** [comment]
Serenity.Web and Serenity.CodeGenerator 1.5.1 packages somehow didn't make it to Nuget gallery, try to update them again please, and rebuild project.

**Comment by volkanceylan** [comment]
Please reopen this if problem still persists.
