### ISSUE TITLE
Error While Uploading Image using ImageUploadEditor

### ISSUE THREAD

**Issue by saeedahmad101** [volkanceylan/Serenity#2586]
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Serenity.Data.ByteArrayField.ValueFromJson(JsonReader reader, Row row, JsonSerializer serializer) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\FieldTypes\ByteArrayField.cs:line 96
   at Serenity.Data.JsonRowConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Row\JsonRowConverter.cs:line 109
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Serenity.Services.JsonFilter.OnActionExecuting(ActionExecutingContext filterContext) in P:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\JsonFilter.cs:line 95
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)

**Comment by saeedahmad101** [comment]
also if we leave image field empty we get this error.

System.ArgumentException: Field 'Image' on row type 'RentACar.RentACar.Entities.CarRow' has a UploadEditor attribute but it is not a String field!
   at Serenity.Services.ImageUploadBehavior.ActivateFor(Row row) in P:\Sandbox\Serene\Serenity\Serenity.Web\Upload\ImageUploadBehavior.cs:line 37
   at Serenity.Services.RowBehaviors`2.get_Default() in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Behavior\RowBehaviors.cs:line 58
   at Serenity.Services.SaveRequestHandler`3.GetBehaviors() in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 30
   at Serenity.Services.SaveRequestHandler`3..ctor() in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 23
   at Serenity.Services.SaveRequestHandler`1..ctor()
   at RentACar.RentACar.Repositories.CarRepository.MySaveHandler..ctor()
   at RentACar.RentACar.Repositories.CarRepository.Create(IUnitOfWork uow, SaveRequest`1 request) in D:\TFSWorkspaces\AutoServices\RentACar\RentACar.Web\Modules\RentACar\Car\CarRepository.cs:line 18
   at RentACar.RentACar.Endpoints.CarController.Create(IUnitOfWork uow, SaveRequest`1 request) in D:\TFSWorkspaces\AutoServices\RentACar\RentACar.Web\Modules\RentACar\Car\CarEndpoint.cs:line 19
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) in P:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs:line 136
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)

**Comment by javaman63** [comment]
Did you read this on your error ? ===> System.ArgumentException: Field 'Image' on row type 'RentACar.RentACar.Entities.CarRow' has a UploadEditor attribute but it is not a **String field**!

IMAGE must be a string type to work with uploadeditor!

**Comment by saeedahmad101** [comment]
yes, as soon i realize that i am using byte[] to store images while serene require it to be string, it got fixed.
thanks for pointing it out.
