### ISSUE TITLE
Authorization has been denied for this request!

### ISSUE THREAD

**Issue by z-combs** [volkanceylan/Serenity#2606]
@volkanceylan

I am continuously getting this error whenever any user other than an admin tries to open a dialog form, even if they have the permission to open it. I have tried each solution to similar issues with no result. What do you need to see to help me with this?

Edit: The error is also being thrown when the same user clicks the 'new' button.

**Comment by fernandocordero** [comment]
Sounds perhaps like your database schema. Is the owner of your database tables, stored procedures different form dbo. Serenity allows to grant permissions per module under the User management. Perhaps yo know this.

**Comment by z-combs** [comment]
I tried clearing all the permissions from the database and clearing the users from the roles and re-applying everything and the problem persisted. Unfortunately I have no idea what permission it's looking for because neither the message or stacktrace include it.

`
Serenity.Services.ValidationError: Authorization has been denied for this request!
at Serenity.Authorization.ValidatePermission(String permission) in P:/Sandbox/Serene/Serenity/Serenity.Core/Authorization/Authorization.cs:line 108
at Serenity.Web.DynamicScript.CheckRights() in P:/Sandbox/Serene/Serenity/Serenity.Web/DynamicScript/DynamicScriptTypes/DynamicScript.cs:line 23
at Serenity.Web.DynamicScriptManager.GetScript(String name) in P:/Sandbox/Serene/Serenity/Serenity.Web/DynamicScript/DynamicScript/DynamicScriptManager.cs:line 94
at Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessScriptRequest(HttpContext context, String scriptKey, String contentType) in P:/Sandbox/Serene/Serenity/Serenity.Web/DynamicScript/DynamicScript/DynamicScriptHandler.cs:line 19
at Serenity.Web.HttpHandlers.DynamicScriptHandler.ProcessRequest(HttpContext context) in P:/Sandbox/Serene/Serenity/Serenity.Web/DynamicScript/DynamicScript/DynamicScriptHandler.cs:line 58
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
`

**Comment by dfaruque** [comment]
This might be the cause,
In that form.cs, there may be a lookup editor and the user has no permission to that lookup.
One possible solution is changing [LookupScript] attribute to
`[LookupScript("xxx", Permission = "?")]`

**Comment by z-combs** [comment]
Doesn't look like it. The only places I have permissions are the: 

- Row
`
[ReadPermission(XXXPermissionKeys.Page_XXX_View)]
[LookupScript("XXX.YYY")]
public sealed class XXXRow : Administration.Entities.XXXRow, IIdRow, INameRow
`

- Page
`
[PageAuthorize(XXXPermissionKeys.Page_XXX_View)]
public class XXXController : Controller
`

- Endpoint
`
[ConnectionKey("Default"), ServiceAuthorize(XXXPermissionKeys.Page_XXX_View)]
public class XXXController : ServiceEndpoint
`

The only other places I have permissions in the modules are for data checks, ie.

`if (!(Authorization.hasPermission("Administration:XXX:YYY:Modify"))) {`
`                this.toolbar.findButton('save-and-close-button').hide();`
`                this.toolbar.findButton('apply-changes-button').hide();`
`            }`

> @dfaruque 
This might be the cause,
In that form.cs, there may be a lookup editor and the user has no permission to that lookup.
One possible solution is changing [LookupScript] attribute to
`[LookupScript("xxx", Permission = "?")]`

I have no `LookupScript`'s that contain that `Permission` line in the module.

**Comment by dfaruque** [comment]
By default lookupscript's permission is ReadPermission (I think)
Please specify `, Permission = "?"` in [LookupScript] to allow anonymous access

**Comment by dfaruque** [comment]
Other words Replace `[LookupScript("xxx")]` with `[LookupScript("xxx", Permission = "?")]`

**Comment by dfaruque** [comment]
See browser console to know which lookupscript is failing to load.

**Comment by dfaruque** [comment]
#118

**Comment by z-combs** [comment]
It worked! Set this in all of my lookup scripts and now everything is working again. Thank you @dfaruque you saved me from another day of trying to hunt down what was happening here.
