### ISSUE TITLE
CORE v3.04 - Crash on new project start - CultureNotFoundException

### ISSUE THREAD

**Issue by VR-Architect** [volkanceylan/Serenity#2639]
Just downloaded the latest CORE version of Serene and it crashes on my new Windows 10 desktop with a Culture error. Seems it is looking for en-UK and in the USA we use en or en-US in our browsers. I got this on a Windows 7 running Internet Explorer 11. BTW, I downloaded the same code on my Windows 10 laptop and it ran fine. 

Target: .NET Core 2.0 

ERROR IN CODE:
```
Startup.cs
line 99 - reqLocOpt.SupportedUICultures = UserCultureProvider.SupportedCultures;
```

ERROR IN BROWSER:
```
An error occurred while starting the application.

CultureNotFoundException: Culture is not supported.
 Parameter name: name
 en-UK is an invalid culture identifier.

System.Globalization.CultureInfo.InitializeFromName(string name, bool useUserOverride)

TypeInitializationException: The type initializer for 'POC1.AppServices.UserCultureProvider' threw an exception.

POC1.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs, line 99

CultureNotFoundException: Culture is not supported. Parameter name: name en-UK is an invalid culture identifier.

System.Globalization.CultureInfo.InitializeFromName(string name, bool useUserOverride)

POC1.AppServices.UserCultureProvider..cctor() in UserCultureProvider.cs
+ 
39.        public static readonly List<CultureInfo> SupportedCultures = new List<CultureInfo>

Show raw exception details 

System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
en-UK is an invalid culture identifier.
   at System.Globalization.CultureInfo.InitializeFromName(String name, Boolean useUserOverride)
   at POC1.AppServices.UserCultureProvider..cctor() in C:\OPT\Projects\POC1\POC1\POC1.Web\Initialization\UserCultureProvider.cs:line 39

TypeInitializationException: The type initializer for 'POC1.AppServices.UserCultureProvider' threw an exception.

POC1.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
+ 
99.            reqLocOpt.SupportedUICultures = UserCultureProvider.SupportedCultures;

System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)

Microsoft.AspNetCore.ApplicationInsights.HostingStartup.ApplicationInsightsLoggerStartupFilter+<>c__DisplayClass0_1.<Configure>b__0(IApplicationBuilder builder)

Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)

Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter+<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)

Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)

Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Show raw exception details 

System.TypeInitializationException: The type initializer for 'POC1.AppServices.UserCultureProvider' threw an exception. ---> System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
en-UK is an invalid culture identifier.
   at System.Globalization.CultureInfo.InitializeFromName(String name, Boolean useUserOverride)
   at POC1.AppServices.UserCultureProvider..cctor() in C:\OPT\Projects\POC1\POC1\POC1.Web\Initialization\UserCultureProvider.cs:line 39
   --- End of inner exception stack trace ---
   at POC1.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\OPT\Projects\POC1\POC1\POC1.Web\Initialization\Startup.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.ApplicationInsights.HostingStartup.ApplicationInsightsLoggerStartupFilter.<>c__DisplayClass0_1.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()


.NET Core 4.6.00001.0 X64 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.0.0-rtm-26452    |    Microsoft Windows 6.1.7601 S    |   Need help? 
```

PACKAGE.json
```
{
  "name": "serene.aspnetcore",
  "version": "1.0.0",
  "description": "POC1 ASP.NET Core",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/volkanceylan/serene"
  },
  "dependencies": {
    "@types/jquery": "^2.0.39",
    "@types/jquery.blockui": "0.0.27",
    "@types/jquery.cookie": "^1.4.28",
    "@types/jquery.validation": "^1.13.32",
    "@types/jqueryui": "^1.11.32",
    "@types/jspdf": "^1.1.31",
    "@types/sortablejs": "^1.3.31",
    "@types/toastr": "^2.1.33",
    "less": "^2.7.2",
    "vue": "^2.1.10"
  },
  "devDependencies": {
    "typescript": "2.4.2"
  },
  "scripts": {
    "tsc": "tsc -p ./tsconfig.json",
    "less": "lessc ./wwwroot/Content/site/site.less ./wwwroot/content/site/site.css"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by volkanceylan** [comment]
Try replacing en-UK with en-GB in UserCultureProvider

**Comment by VR-Architect** [comment]
I walked through the code and the UserCultureProvider.SupportedCultures = null on my desktop. On my laptop, there are 12 values in there. So maybe we need to set some default values for this in the event of a null is returned? 

Also, my desktop is on a highly secured network. My laptop is on open internet.

**Comment by volkanceylan** [comment]
It is not null, it is crashing because it cant create en-UK in your machine, somehow it can in mine

**Comment by VR-Architect** [comment]
I changed it to en-GB but still has null value and crashed. So I drilled into the inner exception and it shows fa-FA is invalid so I commented that out and it works now. I also tested with the en-UK value and it resulted in a null. Changed it back to en-GB and works fine. 

en-UK => en-GB
fa-FA => comment out

**Comment by volkanceylan** [comment]
This commit (2f90b52388fbadfa079dfa4a6c9f8aaac4aa0a0e) should be fixing such problems, even if there are valid cultures that are missing on a system

**Comment by volkanceylan** [comment]
2f90b52388fbadfa079dfa4a6c9f8aaac4aa0a0e

**Comment by volkanceylan** [comment]
https://github.com/volkanceylan/Serene/commit/2f90b52388fbadfa079dfa4a6c9f8aaac4aa0a0e
