### ISSUE TITLE
After Upgrading to AspNetCore2.0 Facing Issue with SqLiteDatabase 

### ISSUE THREAD

**Issue by samdubey** [volkanceylan/Serenity#2669]
**Build is Successful**
D:\Fees>dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Fees.Web -> D:\Fees\bin\Debug\netcoreapp2.0\Fees.Web.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:21.53

**When Run Following Error Occured**

D:\Fees>dotnet run
Using launch settings from D:\Fees\Properties\launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\SAMEER\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.

Unhandled Exception: System.Exception: Error executing migration:
 ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Exists(String template, Object[] args)
   at FluentMigrator.Runner.VersionLoader.LoadVersionInfo()
   at FluentMigrator.Runner.MigrationRunner..ctor(IAssemblyCollection assemblies, IRunnerContext runnerContext, IMigrationProcessor processor)
   at FluentMigrator.Runner.Initialization.TaskExecutor.Initialize()
   at FluentMigrator.Runner.Initialization.TaskExecutor.Execute()
   at Fees.DataMigrations.RunMigrations(String databaseKey) in D:\Fees\Initialization\DataMigrations.cs:line 220
   --- End of inner exception stack trace ---
   at Fees.DataMigrations.RunMigrations(String databaseKey) in D:\Fees\Initialization\DataMigrations.cs:line 227
   at Fees.DataMigrations.Initialize() in D:\Fees\Initialization\DataMigrations.cs:line 28
   at Fees.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in D:\Fees\Initialization\Startup.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Fees.Program.BuildWebHost(String[] args) in D:\Fees\Initialization\Program.cs:line 17
   at Fees.Program.Main(String[] args) in D:\Fees\Initialization\Program.cs:line 12

D:\Fees>

**Comment by samdubey** [comment]
Solved by removing ..\..\App_Data line from SqLite database

**Comment by volkanceylan** [comment]
I think Microsoft.SQLite changed relative folder system, need to have a look
