### ISSUE TITLE
How to add a custom attribute to inform sergen to skip genterator for some class?

### ISSUE THREAD

**Issue by 19317362** [volkanceylan/Serenity#2709]
I have some old controller code. Which is not used for GRID CRUD etc.
And I don't want sergen to generate the TS file. It makes some error in the TS file generated. (Threading, Async related and some model class related).
I've tried to add an attribute in the Serenity.Core project like this;
`using System;

namespace Serenity.ComponentModel
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public sealed class SkipTsAttribute : Attribute
    {
        public SkipTsAttribute()
        {
        }
    }
}
`

Than, I modify the class ServerImportGeneratorBase
`
        protected override void GenerateAll()
        {
            foreach (var assembly in this.Assemblies)
            {
                ....
                foreach (var fromType in types)
                {
                    if (fromType.IsAbstract)
                        continue;
                    **if( fromType.GetCustomAttribute<SkipTsAttribute>() != null)
                    {//added by me to skip
                        continue;
                    }**

`
Than in my ugly controller

`    
[SkipTs]

    public class OldUglyController : ServiceEndpoint
    {`

Then, I remove the reference to NUGET package, add reference to Serenity.Web project, 

Then rebuild all.
During the post build phase, error ocurs.

`16>HiLock.Web -> c:\Users\lele\source\repos\sere20170902\sere\Serenity\App\HiLock.Web\bin\Release\netcoreapp2.0\HiLock.Web.dll
16>Transforming ServerTypings at: c:\Users\lele\source\repos\sere20170902\sere\Serenity\App\HiLock.Web\Imports\ServerTypings
16>
16>Unhandled Exception: System.TypeLoadException: Could not load type 'Serenity.ComponentModel.SkipTsAttribute' from assembly 'Serenity.Core, Version=3.0.5.0, Culture=neutral, PublicKeyToken=null'.
16>   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
16>   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
16>   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
16>   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
16>   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
16>   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
16>   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
16>   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
16>   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
16>   at Serenity.CodeGeneration.ServerImportGeneratorBase.GenerateAll()
16>   at Serenity.CodeGenerator.ServerTypingsCommand.Run(String csproj, List`1 tsTypes)
16>   at Serenity.CodeGenerator.Program.Main(String[] args)
16>c:\Users\lele\source\repos\sere20170902\sere\Serenity\App\HiLock.Web\HiLock.Web.csproj(37,5): warning MSB3073: The command "dotnet sergen servertypings" exited with code -532462766.
16>Done building project "HiLock.Web.csproj".
========== Build: 16 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
`

Than, I tried to replace the dotnet-sergen.exe in .nuget with the new one produced. The same error.
Run dotnet sergen servertypings from command line gives the same error.

What's wrong with me? It's a small modification test.

I think this type of attribute is useful.
Maybe you can add it in the next version.

Thanks a lot.

**Comment by 19317362** [comment]
I've done this by:
copy my version of .dlls to  <user>/.nuget/package/serenity*
eg
.nuget\packages\serenity.codegenerator\3.0.5\lib\netcoreapp2.0
