### ISSUE TITLE
Lookup Editor - Display a different field in the drop down

### ISSUE THREAD

**Issue by TheColonel2688** [volkanceylan/Serenity#2790]
![image](https://user-images.githubusercontent.com/8753759/31819566-3cf333ba-b56b-11e7-8b77-0d8181308399.png)
First:

This is the code from the Row.cs (TimeEntriesRow.cs)

Right Now it displays Job.JobName I would like it to display Job.JobNumber.

I have tried changing TextualField("JobJobName") to TextualField("JobJobNumber") but it does not seem to change anything.

```
        [DisplayName("Job"), NotNull, ForeignKey("[dbo].[Jobs]", "Id"), LeftJoin("jJob"), TextualField("JobJobName")]
        [LookupEditor("Betz.Jobs")]
        public Int32? JobId
        {
            get { return Fields.JobId[this]; }
            set { Fields.JobId[this] = value; }
        }
```

Second: Would it be possible to change the display menu items to a concatenation of 2 fields? 

Like "[JobNumber] - [JobName]"

Third: Can I filter the items in the Menu by Job.Status == 10

Fourth: How can I change the order that the Fields are display in the form? For example how would I move Employee to the Top of the form?

**Comment by Zahar661** [comment]
For example, try
1) In Betz.JobsRow JobName and Status add LookupInclude
2) In TimeEntriesRow LookupEditor(typeof(JobsRow),LookupKey ="JobName",FilterField = "Status",FilterValue ="10")

**Comment by TheColonel2688** [comment]
per you susgestion I tried

in Betz.JobsRow
```
[DisplayName("Job Name"), QuickSearch]
        public String JobName
        {
            get { return Fields.JobName[this]; }
            set { Fields.JobName[this] = value; }
        }

        [LookupInclude]
        [DisplayName("Job Number"), NotNull, QuickSearch]
        public Int32? JobNumber
        {
            get { return Fields.JobNumber[this]; }
            set { Fields.JobNumber[this] = value; }
        }

        [LookupInclude]
        [DisplayName("Status"), NotNull]
        public Int32? Status
        {
            get { return Fields.Status[this]; }
            set { Fields.Status[this] = value; }
        }
```
TimeEntriesRow

```
[DisplayName("Job"), NotNull, ForeignKey("[dbo].[Jobs]", "Id"), LeftJoin("jJob"), TextualField("JobJobNumber")]
        [LookupEditor(typeof(JobsRow), LookupKey = "JobName")] //,LookupKey = "JobName", FilterField = "Status", FilterValue ="10")
        public Int32? JobId
        {
            get { return Fields.JobId[this]; }
            set { Fields.JobId[this] = value; }
        }
```

The editor window would not load

I also tried 
LookupKey = "JobJobName"
LookupKey = "JobJobNumber"
LookupKey = "JobNumber"
LookupKey = "JobName", LookupKey = "JobName", FilterField = "Status", FilterValue ="10")

**Comment by Zahar661** [comment]
![image](https://user-images.githubusercontent.com/26430136/31838067-d776d180-b5e3-11e7-82db-a7de3ab71cad.png)
I would do so:

JobsRow
```
[Expression("CONCAT(CONCAT(JobName, '-'), JobNumber)"), LookupInclude]
public String JobNameNumber
        {
            get { return Fields.JobNameNumber[this]; }
            set { Fields.JobNameNumber[this] = value; }
        }
```


LookupJob
```
using Serenity.ComponentModel;
using Serenity.Data;
using System;


namespace MyProject.Modules.Betz.Scripts
{
    using Betz.Entities;
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;

    [LookupScript("Betz.Job", Expiration = -1, Permission = "*")]
    public class JobLookup : RowLookupScript<JobsRow>
    {
        public JobLookup()
        {
            IdField = "JobId";
            TextField = "JobNameNumber";
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = JobsRow.Fields;
            query.Select(fld.JobNameNumber, fld.JobId)
                .Where(new Criteria(fld.Status) == 10);
        }
    }
}
```
TimeEntriesRow

```
[DisplayName("Job"), NotNull, ForeignKey("[dbo].[Jobs]", "Id"), LeftJoin("jJob"), TextualField("JobJobNumber")]
[LookupEditor(typeof(JobLookup))]
        public Int32? JobId
        {
            get { return Fields.JobId[this]; }
            set { Fields.JobId[this] = value; }
        }
```

**Comment by TheColonel2688** [comment]
I tired your latest suggestion, but the editor window will not load. I placed a break point in the JobLookup.PrepareQuery method and it does get called, but after it returns nothing happens. The editor window should load at that point, but does not.

Is there some other component I am missing? Do I need to do anything is type script?

This is my full code

```
namespace BetzIntranetApplication.Betz.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;
    using Betz.Scripts;

    [ConnectionKey("Betz"), TableName("[dbo].[TimeEntries]")]
    [DisplayName("Time Entries"), InstanceName("Time Entries"), TwoLevelCached]
    [ReadPermission("TimeEntry:Read")]
    [ModifyPermission("TimeEntry:Modify")]
    public sealed class TimeEntriesRow : Row, IIdRow
    {
        [DisplayName("Id"), Identity]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

        [DisplayName("Category"), ForeignKey("[dbo].[WorkCategories]", "Id"), LeftJoin("jCategory"), TextualField("CategoryName")]
        [LookupEditor("Betz.WorkCategories")]
        public Int32? CategoryId
        {
            get { return Fields.CategoryId[this]; }
            set { Fields.CategoryId[this] = value; }
        }

        [DisplayName("Date"), NotNull]
        public DateTime? Date
        {
            get { return Fields.Date[this]; }
            set { Fields.Date[this] = value; }
        }

        
        [DisplayName("Employee"), NotNull, ForeignKey("[dbo].[Employees]", "Id"), LeftJoin("jEmployee"), TextualField("EmployeeFirstName")]
        [LookupEditor("Betz.Employees")]
        public Int32? EmployeeId
        {
            get { return Fields.EmployeeId[this]; }
            set { Fields.EmployeeId[this] = value; }
        }


        [DisplayName("Job"), NotNull, ForeignKey("[dbo].[Jobs]", "Id"), LeftJoin("jJob"), TextualField("JobJobName")]
        [LookupEditor(typeof(JobLookup))]
        public Int32? JobId
        {
            get { return Fields.JobId[this]; }
            set { Fields.JobId[this] = value; }
        }

        [DisplayName("Time Spent Hours"), NotNull]
        public Double? TimeSpentHours
        {
            get { return Fields.TimeSpentHours[this]; }
            set { Fields.TimeSpentHours[this] = value; }
        }

        [DisplayName("Category Name"), Expression("jCategory.[Name]")]
        public String CategoryName
        {
            get { return Fields.CategoryName[this]; }
            set { Fields.CategoryName[this] = value; }
        }
        [DisplayName("Category Parent Id"), Expression("jCategory.[ParentId]")]
        public Int32? CategoryParentId
        {
            get { return Fields.CategoryParentId[this]; }
            set { Fields.CategoryParentId[this] = value; }
        }
        [DisplayName("Employee First Name"), Expression("jEmployee.[FirstName]"), QuickSearch]
        public String EmployeeFirstName
        {
            get { return Fields.EmployeeFirstName[this]; }
            set { Fields.EmployeeFirstName[this] = value; }
        }
        [DisplayName("Employee Last Name"), Expression("jEmployee.[LastName]")]
        public String EmployeeLastName
        {
            get { return Fields.EmployeeLastName[this]; }
            set { Fields.EmployeeLastName[this] = value; }
        }
        [DisplayName("Employee Status"), Expression("jEmployee.[Status]")]
        public Int32? EmployeeStatus
        {
            get { return Fields.EmployeeStatus[this]; }
            set { Fields.EmployeeStatus[this] = value; }
        }
        [DisplayName("Job Customer Id"), Expression("jJob.[CustomerId]")]
        public Int32? JobCustomerId
        {
            get { return Fields.JobCustomerId[this]; }
            set { Fields.JobCustomerId[this] = value; }
        }
        [DisplayName("Job Name"), Expression("jJob.[JobName]")]
        public String JobJobName
        {
            get { return Fields.JobJobName[this]; }
            set { Fields.JobJobName[this] = value; }
        }
        [DisplayName("Job Number"), Expression("jJob.[JobNumber]"), QuickSearch]
        public Int32? JobJobNumber
        {
            get { return Fields.JobJobNumber[this]; }
            set { Fields.JobJobNumber[this] = value; }
        }
        [DisplayName("Job Status"), Expression("jJob.[Status]")]
        public Int32? JobStatus
        {
            get { return Fields.JobStatus[this]; }
            set { Fields.JobStatus[this] = value; }
        }
        IIdField IIdRow.IdField
        {
            get { return Fields.Id; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public TimeEntriesRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field Id;
            public Int32Field CategoryId;
            public DateTimeField Date;
            public Int32Field EmployeeId;
            public Int32Field JobId;
            public DoubleField TimeSpentHours;

            public StringField CategoryName;
            public Int32Field CategoryParentId;

            public StringField EmployeeFirstName;
            public StringField EmployeeLastName;
            public Int32Field EmployeeStatus;

            public Int32Field JobCustomerId;
            public StringField JobJobName;
            public Int32Field JobJobNumber;
            
            public Int32Field JobStatus;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Betz.TimeEntries";
            }
        }
    }
}
```

```
using BetzIntranetApplication.Betz.Entities;
using Serenity.Data;


namespace BetzIntranetApplication.Betz.Scripts
{
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Web;

    [LookupScript("Betz.Job", Expiration = -1, Permission = "*")]
    public class JobLookup : RowLookupScript<JobsRow>
    {
        public JobLookup()
        {
            IdField = "JobId";
            TextField = "JobNameNumber";
        }

        protected override void PrepareQuery(SqlQuery query)
        {
            var fld = JobsRow.Fields;
            query.Select(fld.JobNameNumber, fld.Id)
                .Where(new Criteria(fld.Status) == 10);
        }
    }
```
```
namespace BetzIntranetApplication.Betz.Entities
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using Serenity.Data.Mapping;
    using System;
    using System.ComponentModel;
    using System.IO;

    [ConnectionKey("Betz"), TableName("[dbo].[Jobs]")]
    [DisplayName("Jobs"), InstanceName("Jobs"), TwoLevelCached]
    [LookupScript("Betz.Jobs")]
    [ReadPermission("Job:Read")]
    [ModifyPermission("Job:Modify")]
    public sealed class JobsRow : Row, IIdRow, INameRow
    {
        [DisplayName("Id"), Identity]
        public Int32? Id
        {
            get { return Fields.Id[this]; }
            set { Fields.Id[this] = value; }
        }

        [DisplayName("Customer Id")]
        public Int32? CustomerId
        {
            get { return Fields.CustomerId[this]; }
            set { Fields.CustomerId[this] = value; }
        }

        [LookupInclude]
        [DisplayName("Job Name")]
        public String JobName
        {
            get { return Fields.JobName[this]; }
            set { Fields.JobName[this] = value; }
        }

        [LookupInclude]
        [DisplayName("Job Number"), NotNull]
        public Int32? JobNumber
        {
            get { return Fields.JobNumber[this]; }
            set { Fields.JobNumber[this] = value; }
        }

        [LookupInclude]
        [DisplayName("Status"), NotNull]
        public Int32? Status
        {
            get { return Fields.Status[this]; }
            set { Fields.Status[this] = value; }
        }

        [Expression("CONCAT(CONCAT(JobName, '" +
                    "-'), JobNumber)"), LookupInclude]
        public String JobNameNumber
        {
            get { return Fields.JobNameNumber[this]; }
            set { Fields.JobNameNumber[this] = value; }
        }

        IIdField IIdRow.IdField
        {
            get { return Fields.Id; }
        }

        StringField INameRow.NameField
        {
            get { return Fields.JobName; }
        }

        public static readonly RowFields Fields = new RowFields().Init();

        public JobsRow()
            : base(Fields)
        {
        }

        public class RowFields : RowFieldsBase
        {
            public Int32Field Id;
            public Int32Field CustomerId;
            public StringField JobName;
            public Int32Field JobNumber;
            public Int32Field Status;
            public StringField JobNameNumber;

            public RowFields()
                : base()
            {
                LocalTextPrefix = "Betz.Jobs";
            }
        }
    }
}
```

**Comment by TheColonel2688** [comment]
I have just noticed that I am getting this error on build, it doesn't halt the build however.

Does this have anything to do with my issues?

>  1>Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
> 1>   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
> 1>   at System.Diagnostics.Process.Start()
> 1>   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
> 1>   at Serenity.CodeGenerator.TSTypeLister.List()
> 1>   at Serenity.CodeGenerator.Program.<>c__DisplayClass0_0.<Main>b__1()
> 1>   at Serenity.CodeGenerator.Program.Main(String[] args)

Also. I noticed that there is there is a new version of Serenity 3.3.1 ( I am on 3.2.2) However after I upgrade. none of the grids will load. there are jut blank pages.

**Comment by Zahar661** [comment]
Look City in the Northwind

**Comment by TheColonel2688** [comment]
I think part of my problem was that I needed to install NodeJS 8.7.0. not 100% on that.

The second issue is was that the IdField should have been ="Id" Not ="JobId"

public JobLookup()
        {
            IdField = "Id";
            TextField = "NameNumber";
        }

This was my mistake and I should have noticed sooner.

Thank you very much for your help Zahar661. I would not have gotten this to work with out your assistance.

**Comment by hhernandezCS** [comment]
I need help to load in a LookupEditor two concatenated fields from another Row, I have my following code:

[DisplayName("ActiveIngrActive"), ForeignKey("[Trans].[IngrActive]", "KeyIngrActive"), LeftJoin("jKeyIngrActive"), TextualField("KeyIngrActiveDescription")]
        [LookupEditor(typeof(IngrActiveRow))]]
        public Int32? KeyIngrActive { get => Fields.KeyIngrActive[this]; set => Fields.KeyIngrActive[this] = value; }
        public partial class RowFields { public Int32Field KeyIngrActivo; }

Translated with www.DeepL.com/Translator (free version)
