### ISSUE TITLE
T4 transform; Null reference exception (shows C:\sandbox path which I don't have); VS 2017 15.4.1, SF 2.9.24

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#2828]
Hi all,

today when I wanted to use the T4 transform function I suddenly got a null reference exception when it tries to compile the servertypings.tt.

This is with the newest VS 2017 15.4.1 and SF V2.9.24

**The whole process (high Level) looks like this:**

Transforming template ClientTypes.tt with TextTemplatingFileGenerator ... succeeded.
Transforming template MVC.tt with TextTemplatingFileGenerator ... succeeded.
Transforming **template ServerTypings.tt** with **TextTemplatingFileGenerator ... failed**.

**The full error message is like this:**

Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass17_0.<GenerateRowMetadata>b__2() in C:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.Row.cs:line 67
   at Serenity.Reflection.CodeWriter.InBrace(Action insideBlock) in C:\Sandbox\Serene\Serenity\Serenity.Core\Reflection\CodeWriter.cs:line 45
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateRowMetadata(Type rowType) in C:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.Row.cs:line 59
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateBasicType(Type type) in C:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 137
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass22_1.<GenerateCodeFor>b__1() in C:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 43
   at Serenity.Reflection.CodeWriter.InBrace(Action insideBlock) in C:\Sandbox\Serene\Serenity\Serenity.Core\Reflection\CodeWriter.cs:line 45
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass22_0.<GenerateCodeFor>b__0(Action`1 action) in C:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 41
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateCodeFor(Type type) in C:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 77
   at Serenity.CodeGeneration.ServerImportGeneratorBase.GenerateAll() in C:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\Base\ServerImportGeneratorBase.cs:line 151
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateAll() in C:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 29
   at Microsoft.VisualStudio.TextTemplating1FD20D6C5534CDB07261B0833BE6F62C4E218489725000276AD62B2FAEBDB05B8086990075833D5237A7C625CCFDAF40D070EF739EC1FB2B69FF79C8BF72A590.GeneratedTextTransformation.TransformText()	RAPrintManager.Web	C:\Development\RAPrintManager\RAPrintManager\RAPrintManager.Web\Imports\ServerTypings\ServerTypings.tt	1	

From an "optical" point of view, the ServerTypings.tt file looks ok but if it makes sense (tell me) I can attach it here.

**Hints:** 
(1) The Project builds just fine. 
(2) A Clean Project --> Rebuild didn't resolve this Problem.
(3) A test upgrade to the newest SF 3.3.5didn't resolve this Problem either.
(4) Debugging the ServerTypings.tt reveals that it crashes within the line: **var codeByFilename = generator.Run();** --> I am now stepping into and look where it crashes...

**Intermediate result:**
I have traced it down to a clientside-only Identiy-field (actually I have to dynamically generate an in-memory-only ID field for a table which does not have an identity field and which I cannot alter).

Within the app, this generated ID field works fine - except now for the non-working T4 transform.

I define the client-side field within xyzRow.cs like this:

```cs
        #region calculatedID

        [DisplayName("CalculatedID"), Column("CalculatedID"), Identity, NotMapped]
        public Int32Field CalculatedID { get; set; }
        //public partial class RowFields { public Int32Field CalculatedID; }
        #endregion calculatedID
```

Any help to resolve this is highly welcome :-)

With Kind regards,

John

**Comment by volkanceylan** [comment]
One of yours rows IdField property returns null

**Comment by JohnRanger** [comment]
Hi Volkan,

thanks for your very fast response.

Please see my updated question.

I have already traced it down to an in-memory-generated ID field (exactly as you say - it is in the range of the ID field).

I have defined the in-memory-id field like this:

```cs
        #region calculatedID

        [DisplayName("CalculatedID"), Column("CalculatedID"), Identity, NotMapped]
        public Int32Field CalculatedID { get; set; }
        //public partial class RowFields { public Int32Field CalculatedID; }
        #endregion calculatedID
```

I have tried to follow the examples but obviously missed something essential.

How would I properly define the in-memory ID field so that it auto-generates the ID? IS this at all possible?

Thanks for your further feedback and

With Kind regards,

John

**Comment by volkanceylan** [comment]
Hi John,

I don't understand what you mean by in memory ID field, that's not possible.

Don't return it from your IIdField.IdProperty.

And you can't add properties to Field declarations, that's also pretty wrong usage.

**Comment by JohnRanger** [comment]
Hi Volkan,

ok, maybe I have to reword what I want to achieve.

I have to use a table from an existing (commercial - means unchangable) application which has no Identity field. There is also no usable (unique) other field which I could use as an identity within my Serenity Project.

As I understand (maybe wrongly), Serenity Needs always an identity field to work.

But as only Serenity Needs an ID field (temporarily to work with the table) I wanted Serenity to auto-generate a unique ID "in-memory" so that Serenity works but that the physical table is not altered.

**My goal:**
Use this table without altering it physically from within Serenity.

How can this be accomplished?

(If I remember correctly, this has been asked long ago by somebody else but I could not find the issue or the solution anymore).

With Kind regards,

John

**Comment by JohnRanger** [comment]
As the answer has been given to why this Problem occurs (by Volkan) I close this issue and opens a new one for  the root cause Problem

Thank you Volkan for your confirmation to where the Problem lies.

With Kind regards,

John.

**Comment by volkanceylan** [comment]
You may try concatting fields as an expression field if they are unique together. Otherwise you cant use dialogs/services as they need a way to identify record.
