### ISSUE TITLE
Error when password and username do not match. Help

### ISSUE THREAD

**Issue by billuran** [volkanceylan/Serenity#3117]
Serenity.Services.ValidationError was unhandled by user code
  ErrorCode=AuthenticationError
  HResult=-2146233088
  Message=Invalid username or password
  Source=HealthInsights.Web
  StackTrace:
       at HealthInsights.Membership.Pages.AccountController.<>c__DisplayClass12_0.<Login>b__0() in D:\Projects\HealthInsights\HealthInsights\HealthInsights.Web\Modules\Membership\Account\AccountPage.cs:line 50
       at Serenity.Services.EndpointExtensions.ExecuteMethod[TResponse](Controller controller, Func`1 handler) in C:\Projects\StartSharp\Serenity\Serenity.Web\Mvc\EndpointExtensions.cs:line 64
  InnerException:

**Comment by volkanceylan** [comment]
Works as designed in debug

**Comment by billuran** [comment]
yes but the application itself gets hung up with no alert to the Authentication Error

**Comment by volkanceylan** [comment]
Better read about exception handling and VS debugging
