### ISSUE TITLE
Conversion failed when converting the nvarchar value 'ANTON' to data type int.

### ISSUE THREAD

**Issue by amonragz** [volkanceylan/Serenity#3264]
Hi I'm experiencing this error, could you provide assistance?

Conversion failed when converting the nvarchar value 'ANTON' to data type int.
t System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at Serenity.Data.EntitySqlHelper.ForEach(SqlQuery query, IDbConnection connection, Action callBack) in P:\Sandbox\StartSharp\Serenity\Serenity.Data.Entity\Extensions\EntitySqlHelper.cs:line 229
   at Serenity.Services.ListRequestHandler`3.Process(IDbConnection connection, TListRequest request) in P:\Sandbox\StartSharp\Serenity\Serenity.Services\RequestHandlers\List\ListRequestHandler.cs:line 529
   at Serenity.Services.ListRequestHandler`3.Serenity.Services.IListRequestProcessor.Process(IDbConnection connection, ListRequest request) in P:\Sandbox\StartSharp\Serenity\Serenity.Services\RequestHandlers\List\ListRequestHandler.cs:line 548
   at Serenity.Services.MasterDetailRelationBehavior.OnReturn(IListRequestHandler handler) in P:\Sandbox\StartSharp\Serenity\Serenity.Services\RequestHandlers\IntegratedFeatures\MasterDetail\MasterDetailRelationBehavior.cs:line 194
   at Serenity.Services.ListRequestHandler`3.OnReturn() in P:\Sandbox\StartSharp\Serenity\Serenity.Services\RequestHandlers\List\ListRequestHandler.cs:line 322
   at Serenity.Services.ListRequestHandler`3.Process(IDbConnection connection, TListRequest request) in P:\Sandbox\StartSharp\Serenity\Serenity.Services\RequestHandlers\List\ListRequestHandler.cs:line 541
   at SIGO.Northwind.Repositories.OrderRepository.List(IDbConnection connection, OrderListRequest request) in C:\Users\User\documents\visual studio 2015\Projects\SIGO\SIGO\SIGO.Web\Modules\Northwind\Order\OrderRepository.cs:line 41
   at SIGO.Northwind.Endpoints.OrderController.List(IDbConnection connection, OrderListRequest request) in C:\Users\User\documents\visual studio 2015\Projects\SIGO\SIGO\SIGO.Web\Modules\Northwind\Order\OrderEndpoint.cs:line 43
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) in P:\Sandbox\StartSharp\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs:line 155
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)

Which files should I need to look at?

**Comment by volkanceylan** [comment]
Check field type and data that contains "ANTON".

**Comment by amonragz** [comment]
It’s CustomerID but it’s string in every field even in the table.

**Comment by amonragz** [comment]
Which is the file in the solution that builds the query?

**Comment by minhhungit** [comment]
> Conversion failed when converting the nvarchar value 'ANTON' to data type int.

That mean CustomerID column in your table is INT type I think

**Comment by amonragz** [comment]
Not found, can you provide assistance to find the issue Skype or Hangouts Share Screen? I'll appreciate so much!!  skype: amonragz and hangouts; egutam@gmail.com.

**Comment by amonragz** [comment]
The mistake here was in OrderRow where it was wrong as follows:
        [DisplayName("Details"), MasterDetailRelation(foreignKey: "OrderID"), NotMapped]
        public List<OrderDetailRow> DetailList
        {
            get { return Fields.DetailList[this]; }
            set { Fields.DetailList[this] = value; }
        }

        [DisplayName("Consignees"), MasterDetailRelation(foreignKey: "OrderID"), NotMapped]
        public List<ConsigneeRow> ConsigneeList
        {
            get { return Fields.ConsigneeList[this]; }
            set { Fields.ConsigneeList[this] = value; }
        }
It Should be CustomerID instead of OrderID.
