### ISSUE TITLE
Possible breaking change in 3.5.2

### ISSUE THREAD

**Issue by she-ll-b-rite** [volkanceylan/Serenity#3275]
Hello there. After updating Serenity packages from 3.4.4 to 3.5.2, I'm getting an error in T4 template transformation. Updated all packages including Web Tooling. Project is traditional .NET 45. Any suggestions?

```
Compiling transformation: 'InterfaceImplementation' does not contain a definition for 'FullName' and no extension method 'FullName' accepting a first argument of type 'InterfaceImplementation' could be found (are you missing a using directive or an assembly reference?)	Miscellaneous Files	xxx.Web\Imports\ClientTypes\..\CodeGenerationHelpers.ttinclude	167	
```

**Comment by kilroyFR** [comment]
Volkan already answered: 
replace externalType.Interfaces.Add(intf.FullName) with externalType.Interfaces.Add(intf.InterfaceType.FullName)
=> (it worked for me). 

anyway, Try to update to 3.5.4 (latest version)

**Comment by she-ll-b-rite** [comment]
Thanks for quick response. I tried this and new error results, this time in the ServerTypings.tt

```
Error		Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at Serenity.CodeGeneration.CecilImportGenerator.CanHandleType(TypeDefinition memberType) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs:line 194
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass5_0.<GenerateBasicType>b__1(TypeReference memberType, String memberName, IEnumerable`1 a) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 107
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass5_0.<GenerateBasicType>b__0() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 101
   at Serenity.Reflection.CodeWriter.InBrace(Action insideBlock) in C:\Projects\StartSharp\Serenity\Serenity.Core\Reflection\CodeWriter.cs:line 45
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateBasicType(TypeDefinition type) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 99
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass4_1.<GenerateCodeFor>b__1() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 44
   at Serenity.Reflection.CodeWriter.InBrace(Action insideBlock) in C:\Projects\StartSharp\Serenity\Serenity.Core\Reflection\CodeWriter.cs:line 45
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass4_0.<GenerateCodeFor>b__0(Action`1 action) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 42
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateCodeFor(TypeDefinition type) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 79
   at Serenity.CodeGeneration.CecilImportGenerator.GenerateAll() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs:line 184
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateAll() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 30
   at Microsoft.VisualStudio.TextTemplating94C26B6604256E74C3E65A10A316556AA1B02CC6EB1D555CD8158FBF98FECBED8A38792F0DA15BB9B62C88B9D76FE0C9EA7A88C9EF9B9BAB46BC3461479F9CE1.GeneratedTextTransformation.TransformText()	PWB.Web	C:\Users\antho\Documents\Dev\Projects\PWB\PWB\PWB.Web\Imports\ServerTypings\ServerTypings.tt	1	

```

**Comment by she-ll-b-rite** [comment]
Also updated packages to 3.5.4 and same result.

**Comment by volkanceylan** [comment]
Cecil returns null for some memberType.Resolve() in your project, hard to now which

**Comment by volkanceylan** [comment]
Thanks, that will help a lot

**Comment by minhhungit** [comment]
After upgrade to latest serenity and replace **externalType.Interfaces.Add(intf.InterfaceType.FullName)** , I got this error:

Compiling transformation: 'TypeReference' does not contain a definition for 'InterfaceType' and no extension method 'InterfaceType' accepting a first argument of type 'TypeReference' could be found (are you missing a using directive or an assembly reference?)	
C:\Users\admin\source\repos\Serene2\Serene2.Web\Imports\ClientTypes\..\CodeGenerationHelpers.ttinclude	167

**Comment by volkanceylan** [comment]
You need to also upgrade Serenity.Web.Tooling before doing that change

**Comment by volkanceylan** [comment]
e.g. Cecil under tools\Cecil should be 0.10.0 version

**Comment by volkanceylan** [comment]
If you don't use Saltaralle at all (e.g. C# to Javascript compiler), you may also remove SSTypeLister class in CodeGenerationHelpers.include along with these lines in ServerTypings.tt and ClientTypes.tt:

```
    if (System.IO.File.Exists(solutionDir + @"Marmara.Script.Site\Marmara.Script.Site.csproj"))
    {
        var ssDir = solutionDir + @"Marmara.Script.Site\bin\debug\";
        var ssTypeLister = new SSTypeLister(
            ssDir + "Serenity.Script.Imports.dll",
            ssDir + "Serenity.Script.UI.dll",
            ssDir + "Marmara.Script.Site.dll");
        var ssTypes = ssTypeLister.List();
        foreach (var type in ssTypes)
            generator.AddSSType(type);
    }
```

```

    if (System.IO.File.Exists(solutionDir + @"Marmara.Script.Site\Marmara.Script.Site.csproj"))
    {
        var ssDir = solutionDir + @"Marmara.Script.Site\bin\debug\";
        var ssTypeLister = new SSTypeLister(
            ssDir + "Serenity.Script.Imports.dll",
            ssDir + "Serenity.Script.UI.dll",
            ssDir + "Marmara.Script.Site.dll");
        var ssTypes = ssTypeLister.List();
        foreach (var type in ssTypes)
            generator.AddSSType(type);
    }
````

**Comment by minhhungit** [comment]
After upgrade Serenity.Web.Tooling it worked, thanks !

**Comment by volkanceylan** [comment]
@likeshan168 can you tell me what is the file name of generated .ts file under ServerTypings.ts in old version for this file and share the code generated?

**Comment by likeshan168** [comment]
Is it?
![image](https://user-images.githubusercontent.com/4618372/36412768-89bc2034-1656-11e8-8c7c-a792bf33db63.png)

**Comment by likeshan168** [comment]
![image](https://user-images.githubusercontent.com/4618372/36412827-c52d480a-1656-11e8-9461-89d081742167.png)
![image](https://user-images.githubusercontent.com/4618372/36412831-cd6d4376-1656-11e8-8cfd-137245f26602.png)

**Comment by volkanceylan** [comment]
OK, thanks

**Comment by she-ll-b-rite** [comment]
found something similar
![image](https://user-images.githubusercontent.com/17591095/36412873-1d4c3744-1670-11e8-88b8-2c79dd91a9ba.png)

**Comment by likeshan168** [comment]
and the debug info is 
![image](https://user-images.githubusercontent.com/4618372/36412932-2fab1fb8-1657-11e8-993e-d0a8f5fafa92.png)

**Comment by volkanceylan** [comment]
Can you try with 3.5.5, it should be available in 5 mins+

**Comment by likeshan168** [comment]
ok, I will try when it is available

**Comment by volkanceylan** [comment]
Well it stuck in validating in NuGet server, so might take some time

**Comment by she-ll-b-rite** [comment]
fixed for me thx. issue was the `<SlingRow>` in the `SlingPriceRequest` class definition. TS Class signature now looks like:
```
namespace PWB.SlingMate.Services {
    export interface SlingPriceRequest extends Serenity.ServiceRequest {
        Entity?: SlingRow;
        EntityId?: number;
        IsNew?: boolean;
        DistributorId?: number;
        PriceModelId?: number;
    }
}
```

**Comment by likeshan168** [comment]
it also fix my issue, thanks

**Comment by choss21** [comment]
Same Proble With NetCore version LastVersion :(
