### ISSUE TITLE
Multiple Lookupeditor gives an error in same Row

### ISSUE THREAD

**Issue by ademc** [volkanceylan/Serenity#34]
Hi,

I just discovered Lookupeditor attribute and love it. But I realized that a row can handle only one LookupEditor. When I used multiple Lookupeditor attribute on several field/property, t4 transforming gives an error:

```
Error	1	Running transformation: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Project.Entities.HedeRow' threw an exception. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: lookupType
   at Serenity.ComponentModel.LookupEditorAttribute..ctor(Type lookupType) in c:\Sandbox\Serene\Serenity\Serenity.Core\ComponentModel\PropertyGrid\Editing\BasicEditorTypes.cs:line 217
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimePropertyInfo property, RuntimeType caType)
   at System.Reflection.RuntimePropertyInfo.GetCustomAttributes(Boolean inherit)
   at Serenity.Data.RowFieldsBase.Initialize() in c:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Row\RowFieldsBase.cs:line 368
   at Serenity.Data.RowExtensions.Init[TRowFields](TRowFields rowFields) in c:\Sandbox\Serene\Serenity\Serenity.Data.Entity\Extensions\RowExtensions.cs:line 46
   at Gimnet.Sertifika.Entities.FirmaRow..cctor() in c:\Users\ademca\Documents\Visual Studio 2012\Projects\Gimnet2\Gimnet\Gimnet.Web\Modules\Sertifika\Firma\FirmaRow.cs:line 249
   --- End of inner exception stack trace ---
   at Gimnet.Sertifika.Entities.FirmaRow..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Serenity.PropertyGrid.PropertyItemHelper.GetBasedOnRow(Type type) in c:\Sandbox\Serene\Serenity\Serenity.Data.Entity\PropertyGrid\PropertyItemHelper.cs:line 63
   at Serenity.PropertyGrid.PropertyItemHelper.GetPropertyItemsFor(Type type) in c:\Sandbox\Serene\Serenity\Serenity.Data.Entity\PropertyGrid\PropertyItemHelper.cs:line 18
   at Serenity.CodeGeneration.ScriptFormGenerator.<>c__DisplayClass27_1.<GenerateCode>b__0() in c:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ScriptFormGenerator.cs:line 93
   at Serenity.Reflection.CodeWriter.InBrace(Action insideBlock) in c:\Sandbox\Serene\Serenity\Serenity.Core\Reflection\CodeWriter.cs:line 47
   at Serenity.CodeGeneration.ScriptFormGenerator.GenerateCode() in c:\Sandbox\Serene\Serenity\Serenity.Web\CodeGeneration\ScriptFormGenerator.cs:line 81
   at Microsoft.VisualStudio.TextTemplatingBCDB993AC8CB286F8D6846AB78AD85B7D7613156BF763564781FB67DB2B60DA6195498D7C665D76ACF8E2657D90FF438276B8ADD17DE83AD5A98EDB2339328C3.GeneratedTextTransformation.TransformText()	C:\Users\xxx\Documents\Visual Studio 2012\Projects\xxx\xxx\xxx.Script\Imports\FormContexts\FormContexts.tt	1	1	xxx.Script

```

**Comment by volkanceylan** [comment]
My guess is this is not about using multiple LookupEditor attributes but having a LookupEditor(typeof(SomeRow)) on a form property declaration but having no [LookupScript] attribute on SomeRow, so Serenity can't determine lookup key. Just add a LookupScript attribute on SomeRow.

Here is the code that throws this exception:

```cs
    public partial class LookupEditorAttribute : CustomEditorAttribute
    {
        public LookupEditorAttribute(Type lookupType)
            : base("Lookup")
        {
            var attr = lookupType.GetCustomAttributes(typeof(LookupScriptAttribute), false);
            if (attr.Length == 0)
                throw new ArgumentOutOfRangeException("lookupType");
```

But i'll make the error message more descriptive.

**Comment by ademc** [comment]
You are right. I set lookup script and t4 transformation finished successfully. 

By the way i look for serenity source code when have an error but sometimes -especially t4 transformation times- everything become more blurry. Is this exception clear enough for understanding "for me" or will be more understandable?  

Thank you so much.

**Comment by volkanceylan** [comment]
It is clearly not clear :) As i said, i'll make it more clear by giving information in exception text.

**Comment by volkanceylan** [comment]
Ok, new error message is like this:

'Serene.Northwind.OrderRow' type doesn't have a [LookupScript] attribute, so it can't be used with a LookupEditor!

Hope it's more descriptive...
