### ISSUE TITLE
T4 gives NullReferenceException while NestedType (RowField) is outside the Row class

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#3458]
It will be better to provide some hint to fix that.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at Serenity.CodeGeneration.ServerTypingsGenerator.<EnumerateFieldProperties>d__13.MoveNext() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.Row.cs:line 21
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateRowMembers(TypeDefinition rowType) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.Row.cs:line 38
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass5_0.<GenerateBasicType>b__0() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 102
   at Serenity.Reflection.CodeWriter.InBrace(Action insideBlock) in C:\Projects\StartSharp\Serenity\Serenity.Core\Reflection\CodeWriter.cs:line 45
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateBasicType(TypeDefinition type) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 99
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass4_1.<GenerateCodeFor>b__1() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 44
   at Serenity.Reflection.CodeWriter.InBrace(Action insideBlock) in C:\Projects\StartSharp\Serenity\Serenity.Core\Reflection\CodeWriter.cs:line 45
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass4_0.<GenerateCodeFor>b__0(Action`1 action) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 42
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateCodeFor(TypeDefinition type) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 79
   at Serenity.CodeGeneration.CecilImportGenerator.GenerateAll() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs:line 184
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateAll() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 30
   at Serenity.CodeGeneration.CodeGeneratorBase.Run() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CodeGeneratorBase.cs:line 35
   at Microsoft.VisualStudio.TextTemplating48EB3C88B9E98C52E938109715F727E02BB1CD7E9BE6FA6D75D21444EBE841C197586064301181F677E4FB46DEF3BE1A04773B8A0C04F98C6EEE745AE352F81A.GeneratedTextTransformation.TransformText() in D:\Faruque\Projects\TVLSecurity\TVLSecurity\TVLSecurity.Web\Imports\ServerTypings\ServerTypings.tt:line 26		C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.Row.cs	21	
```

It takes my whole day to identify the cause.
Thanks.

**Comment by dfaruque** [comment]
the suggested lines are not in my code. these line says 
C:\Projects\StartSharp\Serenity.....
which I don't have.

**Comment by volkanceylan** [comment]
I've added a check there (9ef2fa52c29ac46a3ce6695d2315fd46edf3e337). Thanks @dfaruque. Please note that fields must be a subclass of row type, as it is expected for proper initialization.

**Comment by ga5tan** [comment]
@dfaruque Hi, how did you figure out what is the problem?
I cloned solution to VS2019 and having same issue, I cannot even find a stack trace though

**Comment by dfaruque** [comment]
What are you getting?
