### ISSUE TITLE
Exceptions Log: Cannot access a closed file

### ISSUE THREAD

**Issue by kcvincent** [volkanceylan/Serenity#3460]
Cannot access a closed file.
System.ObjectDisposedException
System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Serenity.Logging.FileLogger.InternalFlush() in C:\Projects\StartSharp\Serenity\Serenity.Core\Logging\FileLogger.cs:line 95
    
I enabled the Logger and I got the above error Message randomly.

**Comment by volkanceylan** [comment]
Sorry, can't reproduce that.
