### ISSUE TITLE
MultipleImageUploadEditor not working.

### ISSUE THREAD

**Issue by she-ll-b-rite** [volkanceylan/Serenity#347]
hey there, firstly, love this platform.

I'm having an issue with the MultipleImageUploadEditor, its throwing a runtime exception in the SaveRequestHandler for the entity, specifically in the "base.BeforeSave()" call in the override method. 

The exception is:

> An exception of type 'System.NotImplementedException' occurred in Serenity.Data.Entity.dll but was not handled in user code
> 
> Additional information: The method or operation is not implemented.

The code for the property in the Row Entity is:

```
        [DisplayName("Part Images")]
        [MultipleImageUploadEditor(FilenameFormat = "Part/~", JsonEncodeValue = true)]
        public String PartImages
        {
            get { return Fields.PartImages[this]; }
            set { Fields.PartImages[this] = value; }
        }
```

PartImages is a NVARCHAR(MAX) type in the database.

First line of the stack trace is:

```
System.NotImplementedException was unhandled by user code
  HResult=-2147467263
  Message=The method or operation is not implemented.
  Source=Serenity.Data.Entity
  StackTrace:
       at Serenity.Data.StringField.Serenity.Data.IIdField.get_Item(Row row) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\FieldTypes\StringField.cs:line 102
       at Serenity.Services.MultipleImageUploadBehavior.CopyTemporaryFiles(ISaveRequestHandler handler, UploadedFile[] oldFileList, UploadedFile[] newFileList, FilesToDelete filesToDelete) in P:\Sandbox\Serene\Serenity\Serenity.Web\Upload\MultipleImageUploadBehavior.cs:line 167
       at Serenity.Services.MultipleImageUploadBehavior.OnBeforeSave(ISaveRequestHandler handler) in P:\Sandbox\Serene\Serenity\Serenity.Web\Upload\MultipleImageUploadBehavior.cs:line 115
       at Serenity.Services.SaveRequestHandler`3.BeforeSave() in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 47
       at Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType) in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 283
```

I can send full stack trace if that would help.

Many thanks in advance.

**Comment by volkanceylan** [comment]
Your table needs to have a integer id field for this future to work

**Comment by she-ll-b-rite** [comment]
Ah Ok, I will give that a go. Many thx.

**Comment by she-ll-b-rite** [comment]
Thanks a bunch, that worked a treat.
