### ISSUE TITLE
Impersonation: Munq IocContainer failed to resolve Serenity.Abstractions.IAuthorizationService

### ISSUE THREAD

**Issue by karimhyatt** [volkanceylan/Serenity#3620]
Hi, 

The following impersonation code seems to work fine locally, but fails on Azure. 

Any help with the specific IAuthorizationService error would be welcome.

```
            try
            {
                (Dependency.Resolve<IAuthorizationService>() as ImpersonatingAuthorizationService).Impersonate("admin");

                using (IDbConnection cn = SqlConnections.NewByKey("Sustain"))
                {
                    using (var uow = new UnitOfWork(cn))
                    {

                        // Iterate through all ReportContent Rows and copy all relevant information to new tables

                        var rows = cn.List<ReportContentRow>(q => q.SelectTableFields().SelectNonTableFields());
                        foreach (var row in rows)
                        {
                            // Transfer Content to Link Table
                            TransferMaterialDisclosures(uow, row);
                        }

                        uow.Commit();

                    }
                }

                (Dependency.Resolve<IAuthorizationService>() as ImpersonatingAuthorizationService).UndoImpersonate();
            }
            catch (KeyNotFoundException e)
            {
                StringBuilder sb = new StringBuilder();

                foreach (var key in e.Data.Keys)
                    sb.AppendLine($"Data Key: {key.ToString()}");
                
                sb.AppendLine($"Message: {e.Message}");
                sb.AppendLine($"Hresult: {e.HResult}");
                sb.AppendLine($"Source: {e.Source}");
                sb.AppendLine($"Stacktrace: {e.StackTrace}");

                System.Diagnostics.Trace.TraceError(sb.ToString());
                throw new Exception(e.Message, e);
            }
 ```

The error I get is as follows:

```
Munq IocContainer failed to resolve Serenity.Abstractions.IAuthorizationService
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Collections.Generic.KeyNotFoundException: Munq IocContainer failed to resolve Serenity.Abstractions.IAuthorizationService
```
The trace results as follows:
```
 Error       Message: Munq IocContainer failed to resolve Serenity.Abstractions.IAuthorizationService
Hresult: -2146232969
Source: Serenity.Core
Stacktrace:    at Munq.IocContainer.HandleUnResolved(Exception knfe, String name, Type type)
   at Munq.IocContainer.Resolve(String name, Type type)
   at Munq.IocContainer.Resolve[TType]()
   at ReportBase.Migrations.SustainDB.SustainDB_20180409_184000_ContentDataMigration.MigrateDataUp() in D:\a\1\s\ReportBase\ReportBase.Web\Migrations\SustainDB\SustainDB_20180409_184000_ContentDataMigration.cs:line 48

```
Line 48 is
```
(Dependency.Resolve<IAuthorizationService>() as ImpersonatingAuthorizationService).Impersonate("admin");
```

**Comment by karimhyatt** [comment]
After a LOT of searching for the error, it was an Azure issue which didn't completely clean the web app slot. 
Solved by deleting the slot and re-creating it.
