### ISSUE TITLE
Serenity.Web 3.7.4 Upgrade issue

### ISSUE THREAD

**Issue by dsCloud** [volkanceylan/Serenity#3770]
Hello great guys,

Has anyone encounter issues with the latest update 3.7.4? I have the following errors while trying to Transform T4. This happens either if there is an update to the version or a new project.

**Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.IO.FileNotFoundException: Could not load file or assembly 'Serenity.Web, Version=3.7.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Serenity.Web, Version=3.7.4.0, Culture=neutral, PublicKeyToken=null'
   at Microsoft.VisualStudio.TextTemplatingA12055F8A96EE6C99728F7D5A07E4B36FA7C7634581DADE14C78748E010AC828BA58BD40A8E56151955DCE8264B0E1907AA528712832F191443A4D7F9B1767A8.GeneratedTextTransformation.TransformText()
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.PerformTransformation()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].**	

Kindly assist.

**Comment by volkanceylan** [comment]
Reinstall all packages, clear bin directory, update Serenity.Web.Tooling.
