### ISSUE TITLE
Initial Migration fails with Firebird database

### ISSUE THREAD

**Issue by andrewdenton** [volkanceylan/Serenity#3867]
I've created an initial application (.NET Core) and configured it to point to an existing Firebird database. I've modified the `DataMigrations.cs` to run a migration against an existing database. However, whenever I run the application, it attempts to run the initial migration (creating user tables etc) and it fails with the following exception :-

```
System.Exception
  HResult=0x80131500
  Message=Error executing migration:
/* 20160515072600: DefaultDB_20160515_072600_UserPreferences migrating ======= */

/* Beginning Transaction */
/* CreateTable UserPreferences */
CREATE TABLE UserPreferences (UserPreferenceId INTEGER NOT NULL, UserId BIGINT NOT NULL, PreferenceType VARCHAR(100) NOT NULL, Name VARCHAR(200) NOT NULL, "Value" BLOB SUB_TYPE TEXT, CONSTRAINT PK_UserPreferences PRIMARY KEY (UserPreferenceId))
/* !!! An error occurred executing the following sql:
CREATE TABLE UserPreferences (UserPreferenceId INTEGER NOT NULL, UserId BIGINT NOT NULL, PreferenceType VARCHAR(100) NOT NULL, Name VARCHAR(200) NOT NULL, "Value" BLOB SUB_TYPE TEXT, CONSTRAINT PK_UserPreferences PRIMARY KEY (UserPreferenceId))
The error was unsuccessful metadata update
Table USERPREFERENCES already exists
 */
/* !!! unsuccessful metadata update
Table USERPREFERENCES already exists */
/* !!! unsuccessful metadata update
Table USERPREFERENCES already exists */
/* Rolling back transaction */

  Source=GuardianOnline.Web
  StackTrace:
   at GuardianOnline.DataMigrations.RunMigrations(String databaseKey) in E:\Development\GuardianOnline\GuardianOnline\GuardianOnline.Web\Initialization\DataMigrations.cs:line 232
   at GuardianOnline.DataMigrations.Initialize() in E:\Development\GuardianOnline\GuardianOnline\GuardianOnline.Web\Initialization\DataMigrations.cs:line 27
   at GuardianOnline.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in E:\Development\GuardianOnline\GuardianOnline\GuardianOnline.Web\Initialization\Startup.cs:line 125

Inner Exception 1:
Exception: An error occurred executing the following sql:
CREATE TABLE UserPreferences (UserPreferenceId INTEGER NOT NULL, UserId BIGINT NOT NULL, PreferenceType VARCHAR(100) NOT NULL, Name VARCHAR(200) NOT NULL, "Value" BLOB SUB_TYPE TEXT, CONSTRAINT PK_UserPreferences PRIMARY KEY (UserPreferenceId))
The error was unsuccessful metadata update
Table USERPREFERENCES already exists


Inner Exception 2:
FbException: unsuccessful metadata update
Table USERPREFERENCES already exists

Inner Exception 3:
IscException: unsuccessful metadata update
Table USERPREFERENCES already exists
````
There is no existing table (or any other database object) called UserPreferences. I'm using Firebird 2.5.4

**Comment by andrewdenton** [comment]
Turned out to be a corrupted database. I'd tried two separate copies but they both had the same corruption as they were copied from the same source originally.
