### ISSUE TITLE
ServerTyping.tt failed error

### ISSUE THREAD

**Issue by dudeman972** [volkanceylan/Serenity#3900]
Dear @volkanceylan 
I had everything running on version 2.9.3 in projectX.
Then i create a new project version 3.7.4 call projectY.
I copies all my modules over from projectX to projectY.
I compile and every thing builds.
However, when i generate t4 templates..  The serverTyping.tt fails.  
Can you please assist or point me on how to debug this.  I get the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at Serenity.CodeGeneration.CecilImportGenerator.CanHandleType(TypeDefinition memberType) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs:line 194
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass5_0.<GenerateBasicType>b__1(TypeReference memberType, String memberName, IEnumerable`1 a) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 107
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass5_0.<GenerateBasicType>b__0() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 101
   at Serenity.Reflection.CodeWriter.InBrace(Action insideBlock)
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateBasicType(TypeDefinition type) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 99
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass4_1.<GenerateCodeFor>b__1() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 44
   at Serenity.Reflection.CodeWriter.InBrace(Action insideBlock)
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass4_0.<GenerateCodeFor>b__0(Action`1 action) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 42
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateCodeFor(TypeDefinition type) in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 79
   at Serenity.CodeGeneration.CecilImportGenerator.GenerateAll() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs:line 184
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateAll() in C:\Projects\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 30
   at Microsoft.VisualStudio.TextTemplating998E4DE07ABBBF7091159634D9178D39447E738CE7516113F2BD3FC299731CBE72811B3EDAAECCE68BD544E25A9D646844F72700D3FF2801AE816D426783ACE3.GeneratedTextTransformation.TransformText()	DCM.Web	C:\Users\TV\Documents\Visual Studio 2017\Projects\DCM3\DCM\DCM.Web\Imports\ServerTypings\ServerTypings.tt	1

**Comment by ga5tan** [comment]
check the changelog, there was couple of breaking changes...

**Comment by dudeman972** [comment]
Thanks for reply.  I checked, and only relevant this i found was this:
[BREAKING CHANGE] used const enum feature in TypeScript 2.4 to generate field names in ServerTypings Row.ts. Replace "var fld = SomeRow.Fields" with "import fld = SomeRow.Fields" and move that line to just under "namespace" declaration.

But i don't believe (i could be wrong) that it affects me.  I did a search for "var fld" in *.ts files , and there weren't any that were right under the "namespace" declaration.

**Comment by dudeman972** [comment]
Hey guys, i am really stuck at this, and i which there were some clue or way to debug. Any and all help will be appreciated.

**Comment by ga5tan** [comment]
did  new solution work before u pasted your modules?

**Comment by dudeman972** [comment]
yes, it did.  I started off with a new template

**Comment by dudeman972** [comment]
Hi guys, the issue is still unresolved.  any help in approach to debugging this will be greatly appreciated.

**Comment by dudeman972** [comment]
@volkanceylan assistance please :)

**Comment by dudeman972** [comment]
i see the servertypings code generator in serenity.web,  but how do i debug into it when running t4 templates.

**Comment by ademc** [comment]
I am experiencing same issue. How did you fix @dudeman972 ?
