### ISSUE TITLE
Error Running transformation: Mono.Cecil.AssemblyResolutionException

### ISSUE THREAD

**Issue by zabotiznot** [volkanceylan/Serenity#3924]
Outstanding work on the serenity template, Kudos to @volkanceylan and all the people responsible for this masterpiece.

I've been working with the template for almost 2 years using VS 2013 without issues. This week we decided to upgrade to VS 2017 so we upgraded to the latest serenity update as well (15/9/2018).
When I transform T4 templates the 3rd step ends failing:

![screenshot_1](https://user-images.githubusercontent.com/43406296/45747999-c888c680-bc07-11e8-8eca-51ee6d1cdd17.jpg)

In the error list I receive the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'StackExchange.Exceptional, Version=1.0.0.122, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Serenity.Reflection.CecilUtils.<EnumerateBaseClasses>d__8.MoveNext() in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilUtils.cs:line 85
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Serenity.CodeGeneration.CecilImportGenerator.GenerateAll() in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs:line 147
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateAll() in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 30
   at Microsoft.VisualStudio.TextTemplating00664DE7EE471288B57CC2D5BFCE4748015EB922B75B3165830467F05195FAD205DB303A46524E52EF07C4A9E430F0BBE56814A01B84B303C3B60FEC63AB6A58.GeneratedTextTransformation.TransformText()	***	***\***\***\***\***\***\***\Imports\ServerTypings\ServerTypings.tt	1

It's probably related to the StackExchange.Exceptional.dll but I'm unable to solve it or get past this error.
If anybody could shed any light on this problem, I would greatly appreciate it. Thanks in advance.

**Comment by volkanceylan** [comment]
Try updating Serenity.Web.Tooling package and clear bin directory, rebuild

**Comment by zabotiznot** [comment]
Thanks for your reply @volkanceylan . I finally found the real culprit & managed to fix this issue. As it turned out, it was a network issue that caused trouble only when transforming T4 templates... pretty weird huh...
Anyway, thanks again for this great product.
