### ISSUE TITLE
MissingMethodException get_AllowNegativesByDefault()

### ISSUE THREAD

**Issue by dudeman972** [volkanceylan/Serenity#3929]
Hi,
Can any one help me with this exception.
I created a blank project 3.7.4 and copies modules from an older project (2.9.3) into it.

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Boolean Serenity.ComponentModel.DecimalEditorAttribute.get_AllowNegativesByDefault()'.
  Source=Serenity.Data.Entity
  StackTrace:
   at Serenity.PropertyGrid.BasicPropertyProcessor.SetEditing(IPropertySource source, PropertyItem item) in C:\Users\TV\Documents\Visual Studio 2017\Projects\Serenity-master-3-7-4\Serenity.Data.Entity\PropertyGrid\BasicPropertyProcessor\BasicPropertyProcessor.Editing.cs:line 148
   at Serenity.PropertyGrid.BasicPropertyProcessor.Process(IPropertySource source, PropertyItem item) in C:\Users\TV\Documents\Visual Studio 2017\Projects\Serenity-master-3-7-4\Serenity.Data.Entity\PropertyGrid\BasicPropertyProcessor\BasicPropertyProcessor.cs:line 17

**Comment by JohnRanger** [comment]
Hi @dudeman972 ,

just a general feedback: The way you wanted to "upgrade" a project from a really much older version of SF to a current one is not how it should be done - by my own, painful experience.

If you want to "upgrade" a such "old" version (I am currently myself developping a new project with SF 2.9.24 because I found this version most stable and bug free for what I am doing) then the best way is to completely re-create the project "from scratch" (e.g. let sergen create all the stuff for you) and then you transfer the custom logic from within all of your old xyzGrid.ts, xyzDialog.ts, xyzEndpoint.cs and xyzRepository.cs to the new project.

With this approach, I had the most success myself and -although it may look like a lot of work - was the most efficient way to do it.

With kind regards,

John

**Comment by dudeman972** [comment]
Thanks, I do agree with your approach.
