### ISSUE TITLE
The command "dotnet sergen servertypings" exited with code -532462766

### ISSUE THREAD

**Issue by kazinad** [volkanceylan/Serenity#4050]
After upgrading:

- csproj to netcoreapp2.1
- Microsoft.AspNetCore.App to 2.1.5
- Serenity packages to 3.8.1

the following exception is thrown while building the Serenity web application:

>Transforming ServerTypings at: C:\...\Imports\ServerTypings
>
>Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>   at ICSharpCode.Decompiler.UniversalAssemblyResolver.ResolveInternal(AssemblyNameReference name)
>   at ICSharpCode.Decompiler.UniversalAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
>   at ICSharpCode.Decompiler.UniversalAssemblyResolver.Resolve(AssemblyNameReference name)
>   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
>   at Serenity.Reflection.CecilUtils.<EnumerateBaseClasses>d__8.MoveNext()
>   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
>   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
>   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>   at Serenity.CodeGeneration.CecilImportGenerator.GenerateAll()
>   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateAll()
>   at Serenity.CodeGenerator.ServerTypingsCommand.Run(String csproj, List`1 tsTypes)
>   at Serenity.CodeGenerator.Program.Main(String[] args)
>C:\...\.csproj(102,5): warning MSB3073: The command "dotnet sergen servertypings" exited with code -532462766.

**Comment by kazinad** [comment]
> You didn't probably update Serenity.CodeGenerator, check in CSProj file DotNetCliToolReference

Indeed, I forgot that, thanks.
