### ISSUE TITLE
 Can't load script data: RemoteData.UserData!

### ISSUE THREAD

**Issue by williamhodges** [volkanceylan/Serenity#4056]
I am getting the following error when I try to load a page that references a list of users.
` Can't load script data: RemoteData.UserData!`

I have verified #2950 and my UserEnpoint looks like this:

```csharp
[NonAction, DataScript("UserData", CacheDuration = -1), ServiceAuthorize]
        public ScriptUserDefinition GetUserData()
        {
            var result = new ScriptUserDefinition();
            var user = Authorization.UserDefinition as UserDefinition;

            if (user == null)
            {
                result.Permissions = new Dictionary<string, bool>();
                return result;
            }
...
```

Log from VS Code
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Serenity.Web.DynamicScriptRegistration.<>c__DisplayClass0_2.<Initialize>b__2()
   at Serenity.Web.DataScript.GetScript()
   at Serenity.Web.DynamicScriptManager.Item.GenerateContent()
   at Serenity.Web.DynamicScriptManager.GetScript(String name)
   at Serenity.Web.Middleware.DynamicScriptMiddleware.ReturnScript(HttpContext context, String scriptKey, String contentType)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
Any idea?

**Comment by williamhodges** [comment]
Any ideas from anyone?

**Comment by williamhodges** [comment]
Apologies that I keep commenting on this, but @volkanceylan  do you have any idea? I'm kind of stuck in this sprint due to this bug :\

**Comment by williamhodges** [comment]
I'm also getting the following:

```
1>Could not load file or assembly 'Serenity.Web, Version=3.8.1.0, Culture=neutral, PublicKeyToken=null'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
1>Could not load file or assembly 'Serenity.Core, Version=3.8.1.0, Culture=neutral, PublicKeyToken=null'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
1>Could not load file or assembly 'Serenity.Services, Version=3.8.1.0, Culture=neutral, PublicKeyToken=null'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
1>Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
1>Could not load file or assembly 'Serenity.Data.Entity, Version=3.8.1.0, Culture=neutral, PublicKeyToken=null'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
1>Could not load file or assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)```

Yet they are all installed. I'm getting a `dotnet sergen s exited with code 1`

**Comment by volkanceylan** [comment]
Please read a few issues before, update Serenity.CodeGenerator, DotNetCliToolReference!

**Comment by williamhodges** [comment]
I read all the issues here that were available to read. Here is my following .csproj and as you can see it is up to date to the latest version. So I'm not really sure what else to do at this point.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Firefly.Web</AssemblyName>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <DotNetSergen>dotnet sergen</DotNetSergen>
    <DotNetSergen Condition=" '$(TargetFramework)' == 'net461' AND Exists('..\..\Serenity\Serenity.CodeGenerator\bin\$(Configuration)\$(TargetFramework)\dotnet-sergen.exe')">..\..\Serenity\Serenity.CodeGenerator\bin\$(Configuration)\$(TargetFramework)\dotnet-sergen.exe</DotNetSergen>
    <DotNetSergen Condition=" '$(TargetFramework)' == 'netcoreapp2.1' AND Exists('..\..\Serenity\Serenity.CodeGenerator\bin\$(Configuration)\$(TargetFramework)\dotnet-sergen.dll')">dotnet ..\..\Serenity\Serenity.CodeGenerator\bin\$(Configuration)\$(TargetFramework)\dotnet-sergen.dll</DotNetSergen>
    <TypeScriptToolsVersion>3.0</TypeScriptToolsVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\**\*.sql" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
    <None Update="wwwroot\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="Modules\**\*.Template.html;Modules\**\*.ts.html;Views\Templates\*.html">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="2.0.6" />
    <PackageReference Include="Microsoft.Extensions.PlatformAbstractions" Version="1.1.0" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="3.1.1" />
    <PackageReference Include="MySql.Data" Version="8.0.13" />
    <PackageReference Include="MySql.Data.Entity" Version="6.10.8" />
    <PackageReference Include="NLog" Version="4.5.11" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.7.0" />
    <PackageReference Include="Serenity.CodeGenerator" Version="3.8.1" />
    <PackageReference Include="Serenity.FluentMigrator.Runner" Version="1.6.904" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="2.1.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.1' ">
    <PackageReference Include="EPPlus" Version="4.5.2.1" />
    <PackageReference Include="FastMember" Version="1.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.5" />
    <PackageReference Include="Serenity.Web" Version="3.8.1" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <PackageReference Include="EPPlus" Version="4.5.2.1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.1.1" />
    <PackageReference Include="Serenity.Web.AspNetCore" Version="3.8.1" />
  </ItemGroup>
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.1' ">
    <DefineConstants>$(DefineConstants);COREFX;ASPNETCORE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>$(DefineConstants);ASPNETCORE</DefineConstants>
  </PropertyGroup>
  <Import Project="$(SolutionDir)Serenity\tools\Submodule\Serenity.Submodule.AspNetCore.targets" Condition="Exists('$(SolutionDir)Serenity\tools\Submodule\Serenity.Submodule.AspNetCore.targets')" />
  <Target Name="CreateInputsOutputs" BeforeTargets="BeforeBuild">
    <CreateItem Include="Modules\**\*.ts;Imports\**\*.ts">
      <Output TaskParameter="Include" ItemName="CompileTSCInputs" />
    </CreateItem>
    <CreateItem Include="wwwroot\Content\site\**\*.less">
      <Output TaskParameter="Include" ItemName="CompileSiteLessInputs" />
    </CreateItem>
  </Target>
  <Target Name="NpmInstall" BeforeTargets="BeforeBuild" Condition="!Exists('node_modules\@types\jquery\index.d.ts')">
    <Message Text="Installing NPM packages..." Importance="high"></Message>
    <Exec Command="npm install" />
  </Target>
  <Target Name="TransformMvcClientTypes" BeforeTargets="BeforeBuild">
    <Exec Command="$(DotNetSergen) mvct" ContinueOnError="true" />
  </Target>
  <Target Name="CompileSiteLess" AfterTargets="AfterBuild" Inputs="@(CompileSiteLessInputs)" Outputs="wwwroot\Content\site\site.css">
    <Message Text="Compiling site.less..." Importance="high"></Message>
    <Exec Command="node_modules/.bin/lessc ./wwwroot/Content/site/site.less ./wwwroot/content/site/site.css" ContinueOnError="true" />
  </Target>
  <Target Name="TransformServerTypings" AfterTargets="AfterBuild">
    <Exec Command="$(DotNetSergen) servertypings" ContinueOnError="true" />
  </Target>
  <Target Name="CompileTSC" AfterTargets="AfterBuild" Inputs="@(CompileTSCInputs)" Outputs="wwwroot\Scripts\site\Firefly.Web.js">
    <Message Text="Executing TypeScript compiler..." Importance="high"></Message>
    <Exec Command="&quot;$(TscToolPath.Replace('build\\..\tools\', 'tools\'))\tsc&quot; -p ./tsconfig.json" ContinueOnError="true" />
  </Target>
  <ItemGroup>
    <DotNetCliToolReference Include="Serenity.CodeGenerator" Version="3.8.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```

**Comment by volkanceylan** [comment]
Error says that you don't have a parameterless constructor in your controller class, e.g. on UserEndpoint.cs

As, default code doesn't have a parameterized constructor, you probably added a parameter to that. So, you should notice that and remove the parameter.
