### ISSUE TITLE
Always get (not null)  validation error for enum type

### ISSUE THREAD

**Issue by yaseen-h** [volkanceylan/Serenity#4059]
I created new Row as following:
`SomRowType SomeRow = new SomeRowType()`

One of `SomeRow` fields is of enum type and can accept null value

When try to assign null value to this field as following:
`SomeRow.EnumField = null`

I am getting this error:
![image](https://user-images.githubusercontent.com/7968069/48243794-3a54e380-e3f3-11e8-8dcd-08e9f7f49de7.png)

**Comment by Zahar661** [comment]
SomeRow.EnumField.Value = null

**Comment by volkanceylan** [comment]
You should debug, this makes no sense

**Comment by yaseen-h** [comment]
The the complete exception:

`System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at Lebara360.Sales.Entities.UsersRow.set_BranchTypeId(Nullable`1 value) in E:\EJ\Lebara360\Lebara360\Lebara360.Web\Modules\Sales\Users\UsersRow.cs:line 64
   at Lebara360.WebUsers.Repositories.AspUserRepository.MySaveHandler.AfterSave() in E:\EJ\Lebara360\Lebara360\Lebara360.Web\Modules\WebUsers\AspUser\AspUserRepository.cs:line 148
   at Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType)
   at Lebara360.WebUsers.Repositories.AspUserRepository.Create(IUnitOfWork uow, SaveRequest`1 request) in E:\EJ\Lebara360\Lebara360\Lebara360.Web\Modules\WebUsers\AspUser\AspUserRepository.cs:line 20
   at Lebara360.WebUsers.Endpoints.AspUserController.Create(IUnitOfWork uow, SaveRequest`1 request) in E:\EJ\Lebara360\Lebara360\Lebara360.Web\Modules\WebUsers\AspUser\AspUserEndpoint.cs:line 22
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) in C:\Sandbox\StartSharp\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs:line 151
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_0.<InvokeActionMethodWithFilters>b__0()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)`

And this the field definition:
![image](https://user-images.githubusercontent.com/7968069/48288492-5735f900-e47d-11e8-9df6-4ef8f4797784.png)
