### ISSUE TITLE
Errors on Startup after updating 

### ISSUE THREAD

**Issue by FinlanStudios** [volkanceylan/Serenity#4426]
After updating Serenity to 3.9.8, I'm getting errors on startup that don't make any sense. I've updated .net core to 2.2 and ensured that everything in the .csproj is on the correct version. I get zero errors when rebuilding, only when it starts up.

It seems to be blowing up when initializing Row Fields. It's only this class doing it too. I've also tried creating a new project under Serene, updating it to core 2.2, and had no errors. 

I've copied the stack traces below. 

```
System.InvalidProgramException: Field AeStyleID in type AstragalEdgeRow is null and has no corresponding property in entity!
   at Serenity.Data.RowFieldsBase.Initialize() in P:\Sandbox\StartSharp\Serenity\Serenity.Data.Entity\Row\RowFieldsBase.cs:line 219
   at Serenity.Data.RowExtensions.Init[TRowFields](TRowFields rowFields) in P:\Sandbox\StartSharp\Serenity\Serenity.Data.Entity\Extensions\RowExtensions.cs:line 36
   at ApexCore.ApexCore.Entities.AstragalEdgeRow..cctor() in C:\Users\Travis.AMS\Dropbox\ApexCore\ApexCore\ApexCore.Web\Modules\ApexCore\AstragalEdge\AstragalEdgeRow.cs:line 551
```
```
System.RuntimeTypeHandle.CreateInstance(RuntimeType type, bool publicOnly, bool wrapExceptions, ref bool canBeCached, ref RuntimeMethodHandleInternal ctor)
System.RuntimeType.CreateInstanceSlow(bool publicOnly, bool wrapExceptions, bool skipCheckThis, bool fillCache)
System.Activator.CreateInstance(Type type, bool nonPublic, bool wrapExceptions)
Serenity.Data.RowRegistry.Initialize() in RowRegistry.cs
Serenity.Data.RowRegistry.EnsureRegistry() in RowRegistry.cs
Serenity.Data.RowRegistry.EnumerateRows()+MoveNext()
Serenity.Localization.EntityLocalTexts.AddRowTexts(ILocalTextRegistry registry, string languageID) in EntityLocalTexts.cs
ApexCore.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
            textRegistry.AddRowTexts();
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter+<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

```

```
System.RuntimeTypeHandle.CreateInstance(RuntimeType type, bool publicOnly, bool wrapExceptions, ref bool canBeCached, ref RuntimeMethodHandleInternal ctor)
System.RuntimeType.CreateInstanceSlow(bool publicOnly, bool wrapExceptions, bool skipCheckThis, bool fillCache)
System.Activator.CreateInstance(Type type, bool nonPublic, bool wrapExceptions)
Serenity.Data.RowRegistry.Initialize() in RowRegistry.cs
Serenity.Data.RowRegistry.EnsureRegistry() in RowRegistry.cs
Serenity.Data.RowRegistry.EnumerateRows()+MoveNext()
Serenity.Localization.EntityLocalTexts.AddRowTexts(ILocalTextRegistry registry, string languageID) in EntityLocalTexts.cs
ApexCore.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
            Dependency.SetResolver(new AppServices.DependencyResolver(app.ApplicationServices));
            var textRegistry = app.ApplicationServices.GetRequiredService<ILocalTextRegistry>();
            textRegistry.AddNestedTexts();
            textRegistry.AddNestedPermissions();
            textRegistry.AddEnumTexts();
            textRegistry.AddRowTexts();
            var contentRoot = env.ContentRootPath;
            textRegistry.AddJsonTexts(System.IO.Path.Combine(env.WebRootPath, "Scripts/serenity/texts".Replace('/', Path.DirectorySeparatorChar)));
            textRegistry.AddJsonTexts(System.IO.Path.Combine(env.WebRootPath, "Scripts/site/texts".Replace('/', Path.DirectorySeparatorChar)));
            textRegistry.AddJsonTexts(System.IO.Path.Combine(env.ContentRootPath, "App_Data/texts".Replace('/', Path.DirectorySeparatorChar)));
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter+<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by FinlanStudios** [comment]
I'm an idiot. Property & Field name had different cases, which caused the issue.
