### ISSUE TITLE
Error in Transform All T4 Templates

### ISSUE THREAD

**Issue by shaileshbc** [volkanceylan/Serenity#4536]
After creating Application, just run "Transform All T4 Templates" it gives following error in Visual Studio 2019 Community Edition ( version 16.1.6 ) Typescript Tools - 16.0.10506.2004.

Running transformation: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.TextTemplatingB2AA89C5DAF40C570D44F15C0C6F3F51EE3B6DA3BAA7ABF2675E517D559AAE0927B7BDBA378853212507C207405C26C23373BC70570A6AEFA966FA466BC29016.GeneratedTextTransformation.TypeScriptCompiler.DetermineNodePath()
   at Microsoft.VisualStudio.TextTemplatingB2AA89C5DAF40C570D44F15C0C6F3F51EE3B6DA3BAA7ABF2675E517D559AAE0927B7BDBA378853212507C207405C26C23373BC70570A6AEFA966FA466BC29016.GeneratedTextTransformation.TypeScriptCompiler.Compile(String workingDirectory, String arguments)
   at Microsoft.VisualStudio.TextTemplatingB2AA89C5DAF40C570D44F15C0C6F3F51EE3B6DA3BAA7ABF2675E517D559AAE0927B7BDBA378853212507C207405C26C23373BC70570A6AEFA966FA466BC29016.GeneratedTextTransformation.TransformText()	LinenTracking.Web	F:\VSTrialProjects\Serenity_Projects\LinenTracking\LinenTracking\LinenTracking.Web\Imports\ServerTypings\ServerTypings.tt	1	

ServerTypings.tt starts with
<#@ template debug="false" hostspecific="true" language="C#" #>
<#@ assembly name="System.Core" #>
<#@ assembly name="$(TargetDir)Newtonsoft.Json.dll" #>
can anybody tell me why this issue occurs 
regards
Shailesh

**Comment by hubeyb** [comment]
if you can build your project successfully, 
then firstful look at the errors list in visual studio, if you see any error please fix them.
and then look at .ts files whether anyone has error. 
If no error, then close all .ts files then try to rebuild the project.

if error occurs please share your Error List window output.

**Comment by shaileshbc** [comment]
It was error in environmental variables, after fixing it, project compiled successfully.
Thanks
shailesh
