### ISSUE TITLE
Upgrade from 3.4.4 to 3.5.1

### ISSUE THREAD

**Issue by XDDDev** [volkanceylan/Serenity#4702]
Hi,

When I try to upgrade from v3.4.4 to v3.5.1, I am getting following error when transforming T4 Templates (ServerTypings.tt at `var codeByFilename = generator.Run();`)

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at Serenity.CodeGeneration.CecilImportGenerator.EnqueueType(TypeDefinition type) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs:line 45
   at Serenity.CodeGeneration.ServerTypingsGenerator.HandleMemberType(TypeReference memberType, String codeNamespace, StringBuilder sb) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.MemberType.cs:line 129
   at Serenity.CodeGeneration.CecilImportGenerator.MakeFriendlyReference(TypeReference type, String codeNamespace, StringBuilder sb) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs:line 330
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateBasicType(TypeDefinition type) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 96
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass4_1.<GenerateCodeFor>b__1() in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 44
   at Serenity.Reflection.CodeWriter.InBrace(Action insideBlock) in C:\Sandbox\StartSharp\Serenity\Serenity.Core\Reflection\CodeWriter.cs:line 45
   at Serenity.CodeGeneration.ServerTypingsGenerator.<>c__DisplayClass4_0.<GenerateCodeFor>b__0(Action`1 action) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 42
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateCodeFor(TypeDefinition type) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 79
   at Serenity.CodeGeneration.CecilImportGenerator.GenerateAll() in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs:line 184
   at Serenity.CodeGeneration.ServerTypingsGenerator.GenerateAll() in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\ServerTypings\ServerTypingsGenerator.cs:line 30
   at Serenity.CodeGeneration.CodeGeneratorBase.Run() in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CodeGeneratorBase.cs:line 35
   at Microsoft.VisualStudio.TextTemplating9FCE30FC490E6C07C364A8CF182B6DAE5A97CAFC5591A3E242E71F7302B003EF6662F223C6C37A145853DF6ADA8B7787061305B8CAF602B69E1E25CDB1399729.GeneratedTextTransformation.TransformText() in E:\Build\SR.Web\Modules\Common\Imports\ServerTypings\ServerTypings.tt:line 32		C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\CodeGeneration\Base\CecilImportGenerator.cs	45	
`

FYI: All serenity Packages are upgraded to v3.5.1 except Serenity.Web.Assets.
Mono.Cecil.dll under Tools Folder is v0.10.0.0-beta7

Please help to fix this issue.

**Comment by XDDDev** [comment]
Upgrading to latest version fixed this issue
