### ISSUE TITLE
No matching action was found on controller

### ISSUE THREAD

**Issue by ga5tan** [volkanceylan/Serenity#4814]
I am seeing this error:

> No matching action was found on controller 'Project.Common.Pages.DashboardController'. This can happen when a controller uses RouteAttribute for routing, but no action on that controller matches the request.

in Exception log quite frequently. Any idea why it's there, how does it happen and how can I fix it?
ULR logged is "/"

whole stacktrace logged is:
`System.Web.HttpException (0x80004005): No matching action was found on controller 'Project.Common.Pages.DashboardController'. This can happen when a controller uses RouteAttribute for routing, but no action on that controller matches the request.
   at System.Web.Mvc.Controller.HandleUnknownAction(String actionName)
   at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

**Comment by kilroyFR** [comment]
Getting same issue on 'Membership.Pages.AccountController' for /Account/KeepAlive url

**Comment by Nathan2020-0126** [comment]
Can you provide more details information? like the url, the code in 'Project.Common.Pages.DashboardController'

**Comment by ga5tan** [comment]
URL is "/" (without quotes

code is
`
namespace IDI5.Common.Pages
{
    using Serenity;
    using Serenity.Data;
    using System;
    using System.Web.Mvc;

    [RoutePrefix("Dashboard"), Route("{action=index}")]
    public class DashboardController : Controller
    {
        [Authorize, HttpGet, Route("~/")]
        public ActionResult Index()
        {
            var cachedModel = new DashboardPageModel()
            {
            };

            return View(MVC.Views.Common.Dashboard.DashboardIndex, cachedModel);
        }

        //180604 byG - route for Public Home
        [Route("PublicHome")]
        public ActionResult PublicHome()
        {
            return View(MVC.Views.Common.Dashboard.PublicHomeIndex);
        }

        
    }
}
`

**Comment by sayuga** [comment]
Remove "[Route("PublicHome")]" and try again. I do believe that is your current issue. if you are going to simply add references to multiple pages within the same controller, just add them as  

...
    public ActionResult PublicHome()
    {
        return View(MVC.Views.Common.Dashboard.PublicHomeIndex);
    }
...

**Comment by volkanceylan** [comment]
This is sometimes caused by search engine crawlers requesting the page with OPTION header instead of GET headers, check logs to see if request verb is OPTION, if so need to add that verb as well.

**Comment by ga5tan** [comment]
mostly I see with with HEAD method.
do I just need to add that into tag?

**Comment by volkanceylan** [comment]
Yes probably
