### ISSUE TITLE
GUID Problem (Create/Update)

### ISSUE THREAD

**Issue by awesomegithubusername** [volkanceylan/Serenity#517]
Hi;

I'm getting an error when Creating/Updating a form with a uniqueidentifier ID (GUID). The list handler works fine if I create a row directly from SQLServer. My Json (fiddler to the rescue:) ) looks something like this {"Entity":{"xyzId":"f78b4b2b-7ff2-4c3f-b984-55de933653cc","xyzField":"125","TenantId":1}}.

This is the error :

Details=System.FormatException: Unrecognized Guid format.

   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)

   at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)

   at System.Guid.Parse(String input)

   at Serenity.Data.GuidField.ValueFromJson(JsonReader reader, Row row, JsonSerializer serializer) in C:\Projects\Serene\Serenity\Serenity.Data.Entity\FieldTypes\GuidField.cs:line 53

   at Serenity.Data.JsonRowConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\Projects\Serene\Serenity\Serenity.Data.Entity\Row\JsonRowConverter.cs:line 109

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)

   at Serenity.Services.JsonFilter.OnActionExecuting(ActionExecutingContext filterContext) in C:\Projects\Serene\Serenity\Serenity.Web\Mvc\JsonFilter.cs:line 55

   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)

   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()

   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)

   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()

   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)

   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)

**Comment by volkanceylan** [comment]
That guid looks correct. Are you sure XyzId is GuidField while XyzField is IntegerField/StringField?

**Comment by awesomegithubusername** [comment]
Yes volkanceylan:

 [DisplayName("xyz Id"), Column("xyzId"), Identity]
         public Guid? xyzId
        {
            get { return Fields.xyzId[this]; }
            set { Fields.xyzId[this] = value; }
        }

 [DisplayName("XyzField"), Column("XyzField"), Size(100), QuickSearch]
        public String XyzField
        {
            get { return Fields.XyzField[this]; }
            set { Fields.XyzField[this] = value; }
        }

//
 IIdField IIdRow.IdField
        {
            get { return Fields.xyzId; }
        }

StringField INameRow.NameField
        {
            get { return Fields.XyzField; }
        }
//

public class RowFields : RowFieldsBase
        {
            //
            public readonly GuidField xyzId;
            public readonly StringField XyzField;
           //
         }

**Comment by awesomegithubusername** [comment]
![error](https://cloud.githubusercontent.com/assets/13295503/14277769/959395a6-fb1c-11e5-9402-1194d3fa046c.png)

**Comment by volkanceylan** [comment]
This column shouldnt have identity attribute, only primarykey

**Comment by 107295472** [comment]
@awesomegithubusername  guid You can do?

**Comment by 107295472** [comment]
I'm trying guid

**Comment by 107295472** [comment]
database uniqueidentifier type   c# guid

**Comment by awesomegithubusername** [comment]
> This column shouldnt have identity attribute, only primarykey

Changed Identity to PrimaryKey. Still getting the error.

**Comment by awesomegithubusername** [comment]
> @awesomegithubusername guid You can do?

Apparently, yeah. Having issues to save and update forms, though.

**Comment by awesomegithubusername** [comment]
> @awesomegithubusername guid You can do?

Apparently, yeah. Having issues to save and update forms, though.

**Comment by 107295472** [comment]
I don't know how to update guid,Update also has to assign guid

**Comment by 107295472** [comment]
Add no problem guid, Update is

**Comment by awesomegithubusername** [comment]
> Add no problem guid, Update is

I can't create a form with a guid primarykey. I can, however, list a row created directly on SQLServer.

**Comment by 107295472** [comment]
database uniqueidentifier

**Comment by 107295472** [comment]
[DisplayName("ID"), Column("UserId"),PrimaryKey]
        public Guid? UserId
        {
            get { return Fields.UserId[this]; }
            set { Fields.UserId[this] = value; }
        }

**Comment by awesomegithubusername** [comment]
> database uniqueidentifier

What about it, man. I'm not following you.

**Comment by 107295472** [comment]
Did not understand

**Comment by awesomegithubusername** [comment]
> Did not understand

What are you trying to achieve?

**Comment by 107295472** [comment]
My is guid, but can not update

**Comment by awesomegithubusername** [comment]
> My is guid, but can not update  

Can you add a row via serenity Interface (by clicking on New entity button)?

**Comment by 107295472** [comment]
Guid  update  Where to assign

**Comment by volkanceylan** [comment]
Please update to 1.9.28, just found an error with JSON serialization, but it shouldn't give error you wrote, should say something like SomeId field is required. Are you manually entering guids?

**Comment by awesomegithubusername** [comment]
Thanks a lot, volkanceylan. It worked!

**Comment by 107295472** [comment]
guid  manually   yes

**Comment by 107295472** [comment]
@volkanceylan  /// <summary>
        /// Generates a guid based on the current date/time
        /// http://stackoverflow.com/questions/1752004/sequential-guid-generator-c-sharp
        /// </summary>
        /// <returns></returns>
        public static Guid SequentialGuid()
        {
            var tempGuid = Guid.NewGuid();
            var bytes = tempGuid.ToByteArray();
            var time = DateTime.Now;
            bytes[3] = (byte)time.Year;
            bytes[2] = (byte)time.Month;
            bytes[1] = (byte)time.Day;
            bytes[0] = (byte)time.Hour;
            bytes[5] = (byte)time.Minute;
            bytes[4] = (byte)time.Second;
            return new Guid(bytes);
        }

**Comment by volkanceylan** [comment]
@107295472 just update to 1.9.28

**Comment by 107295472** [comment]
okay
