### ISSUE TITLE
Sergen crashes with System.NullreferenceException

### ISSUE THREAD

**Issue by JohnRanger** [volkanceylan/Serenity#5258]
Hi all,

new Serene .net core 3.1 project just deployed and can successfully start the default project, log in and browse through the admin menu.

Trying now to generate code for some custom tables.

Sergen freezes after displaying the connections when running directly within package manager console.

When running from a .net core 7.0.3 powershell outside of Visual Studio, I can then successfully navigate through all the questions - but when it comes to the point to effectively create the code for the desired table, sergen crashes with the following message:

---------------

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Serenity.CodeGenerator.RowGenerator.<>c__DisplayClass5_3.<GenerateModel>b__12(ForeignKeyInfo k) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\Generator\RowGenerator.cs:line 264
   at System.Collections.Generic.List`1.Find(Predicate`1 match)
   at Serenity.CodeGenerator.RowGenerator.GenerateModel(IDbConnection connection, String tableSchema, String table, String module, String connectionKey, String entityClass, String permission, GeneratorConfig config) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\Generator\RowGenerator.cs:line 264
   at Serenity.CodeGenerator.GenerateCommand.Run(String csproj, String[] args) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\Commands\GenerateCommand.cs:line 388
   at Serenity.CodeGenerator.Program.Main(String[] args) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\Program.cs:line 104

------------------------

The Directory C:\Sandbox\... I don't know - but have seen this directory mentioned within old serenity issues. Seems to be from the dev environment of Volkan.

Additional info: The RDMS system is in this case a MySQL 8 system. I have read in the following place that "as of writing" (but that is beginning of 2020) Sergen core does not yet support MySql. Has this been resolved in the meantime?

EDIT: The same crash occurs with an older "full .net" GUI version of sergen (3.12.6.0).

Thanks for your feedback and

with kind regards,

John

**Comment by JohnRanger** [comment]
Sorry, have just discovered that there is now a sergen within the Webapp itself. This one works without any problems.

With kind regards,

John
