### ISSUE TITLE
Migrationg project to 2.0.3 ( t4 templates transformation: MsieJavaScriptEngine.JsRuntimeException)

### ISSUE THREAD

**Issue by awesomegithubusername** [volkanceylan/Serenity#541]
Hi;

I can't transform t4 templates. I'm getting this error:

Error		Running transformation: MsieJavaScriptEngine.JsRuntimeException: Script threw an exception: TypeError: Unable to get property 'length' of undefined or null referenceTypeError: Unable to get property 'length' of undefined or null reference
   at getBaseType (Unknown script code:64:57)
   at classToExternalType (Unknown script code:326:13)
   at visitNode (Unknown script code:375:29)
   at Anonymous function (Unknown script code:390:58)
   at visitEachNode (Unknown script code:7195:17)
   at forEachChild (Unknown script code:7350:17)
   at visitNode (Unknown script code:390:17)
   at Anonymous function (Unknown script code:390:58)
   at visitNode (Unknown script code:7183:13)
   at forEachChild (Unknown script code:7447:17)
   at MsieJavaScriptEngine.JsRt.Ie.ChakraIeJsRtJsEngine.InvokeScript[T](Func`1 func)
   at MsieJavaScriptEngine.JsRt.Ie.ChakraIeJsRtJsEngine.Evaluate(String expression)
   at MsieJavaScriptEngine.MsieJsEngine.Evaluate[T](String expression)
   at Microsoft.VisualStudio.TextTemplating833F0E0806575BBBE02D80DB6152D798CA818415080B80EEB94229CDC6FB615064FE2F7BCD45EFEE89F767E8D7E1EC7795D9FA4397F886EBAE6C30F2551FFE87.GeneratedTextTransformation.TSTypeLister.List()
   at Microsoft.VisualStudio.TextTemplating833F0E0806575BBBE02D80DB6152D798CA818415080B80EEB94229CDC6FB615064FE2F7BCD45EFEE89F767E8D7E1EC7795D9FA4397F886EBAE6C30F2551FFE87.GeneratedTextTransformation.TransformText()

I followed your migration tutorial. Is there something I am missing?

**Comment by volkanceylan** [comment]
Thanks for stack trace, probably found the location, can you update to 2.0.4

**Comment by awesomegithubusername** [comment]
Thanks volkan, it worked. Although for some reason, CustomerID wasn't generated in OrderForm and I was getting compiling error. I added it manually, rebuild the solution, opened it, stopped the execution, removed the added line, transformed t4 templates and voila: the CustomerID did get generated this time. Weird.

**Comment by volkanceylan** [comment]
There may be some glitches at start. It was really challenging to make 4 different languages work together, C#, Saltaralle, TypeScript and Javascript in the end.

**Comment by awesomegithubusername** [comment]
Yeah I hear ya man. I most certainly appreciate your effort. I watched BUILD's "What's New in TypeScript?" https://channel9.msdn.com/Events/Build/2016/B881](url) and I think I'm sold. Best of luck.

**Comment by Deeplalka** [comment]
I'm too geting following error:
Running transformation: MsieJavaScriptEngine.JsRuntimeException: Object expected
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.InvokeScript[T](Func`1 func)
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.Evaluate(String expression)
   at MsieJavaScriptEngine.MsieJsEngine.Evaluate(String expression)
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TSTypeLister.SetupJsEngine() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude:line 251
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TSTypeLister.List() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude:line 262
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TransformText() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\ServerTypings.tt:line 32		E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude	251	
 can any one gaide me for this please

im using win7 64 bit os and vs2017 community with sql server 2008 and google chrome leatest version
