### ISSUE TITLE
Issue Transforming T4 Template 

### ISSUE THREAD

**Issue by 04071967** [volkanceylan/Serenity#600]
Hi

Wanted to work with new updated Template

Unistalled the old one from VS, then added it back this new extension

Installed TypeScript_Dev14Full

Created a dummy project, Build All was fine 

but Transform All T4 Template hits the following error, Please guide

Running transformation: MsieJavaScriptEngine.JsRuntimeException: 'JSON' is undefined
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.InvokeScript[T](Func`1 func)
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.Evaluate(String expression)
   at MsieJavaScriptEngine.MsieJsEngine.Evaluate[T](String expression)
   at Microsoft.VisualStudio.TextTemplating6288221C5D84DD43F581C423CA10D6174509326B2570F0532E013FFC31200267C7135B156F19DF90298406EB81C867B1FCA3000964A56B404A36871D420F7F68.GeneratedTextTransformation.TSTypeLister.List()
   at Microsoft.VisualStudio.TextTemplating6288221C5D84DD43F581C423CA10D6174509326B2570F0532E013FFC31200267C7135B156F19DF90298406EB81C867B1FCA3000964A56B404A36871D420F7F68.GeneratedTextTransformation.TransformText()	SolutionDomain.Script	D:\serene2\Explore\SolutionDomain\SolutionDomain\SolutionDomain.Script\Imports\ServerImports\ServerImports.tt	1

**Comment by volkanceylan** [comment]
1.8 not 1.4

**Comment by volkanceylan** [comment]
Btw, this may not be related to typescript version. You should upgrade anyway, but probably you are not using Windows 10, and have internet explorer only (no edge), so i guess it doesn't have JSON javascript class. What is IE version you use?

**Comment by 04071967** [comment]
I am using Windows 7 with IE 8

**Comment by volkanceylan** [comment]
http://caniuse.com/#feat=json

Yep, IE8 doesn't have JSON by default. I should load json2.js

**Comment by 04071967** [comment]
Added json2.js from https://www.nuget.org/packages/json2

not helping.

**Comment by volkanceylan** [comment]
No, it should be loaded into IE engine that is used to parse typescript code. You can't do it that way. Try this till next version:

Open YourProject.Web\tools\JsEngine\typeScriptServices.js file

Copy this file content and paste it at the start of typeScriptServices.js file

https://raw.githubusercontent.com/douglascrockford/JSON-js/master/json2.js

**Comment by volkanceylan** [comment]
Or better install IE11

**Comment by volkanceylan** [comment]
Should be resolved with 2.0.12

**Comment by ducthanhnguyen** [comment]
I also had a problem with transforming T4 template. My project run well on Windows 10/2012 Server, but on Windows 7,  I got this error in ServerTypings.tt (I added json2 to typeScriptServices.js). Please help!
Error		Running transformation: MsieJavaScriptEngine.JsRuntimeException: [object Error]undefined
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.InvokeScript[T](Func`1 func)
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.Evaluate(String expression)
   at MsieJavaScriptEngine.MsieJsEngine.Evaluate[T](String expression)
   at Microsoft.VisualStudio.TextTemplating62346F23499C2634C85A380629A4B4A9608798FAA966D671EA506B27967DA89E7446030E80DE1A2B65CD2582B14573275C836F1B366A35C967FB801BED30EA57.GeneratedTextTransformation.TSTypeLister.List()
   at Microsoft.VisualStudio.TextTemplating62346F23499C2634C85A380629A4B4A9608798FAA966D671EA506B27967DA89E7446030E80DE1A2B65CD2582B14573275C836F1B366A35C967FB801BED30EA57.GeneratedTextTransformation.TransformText()

**Comment by Estrusco** [comment]
Have you installed Typescript in this machine?

**Comment by volkanceylan** [comment]
Don't modify typeScriptServices.js. IE10 should also work.

**Comment by ducthanhnguyen** [comment]
@Estrusco: Yes, I have Visual Studio 2015 Update 3 installed on that machine and it transformed MVC.tt successully.
@volkanceylan: OK. I'll try IE10 to see if it works. Thanks!

**Comment by ducthanhnguyen** [comment]
Installing IE10 or IE11 on Win7 will fix the error when transforming T4 template.

**Comment by Deeplalka** [comment]
I'm too geting following error:
Running transformation: MsieJavaScriptEngine.JsRuntimeException: Object expected
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.InvokeScript[T](Func`1 func)
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.Evaluate(String expression)
   at MsieJavaScriptEngine.MsieJsEngine.Evaluate(String expression)
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TSTypeLister.SetupJsEngine() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude:line 251
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TSTypeLister.List() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude:line 262
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TransformText() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\ServerTypings.tt:line 32		E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude	251	
 can any one gaide me for this please

**Comment by Deeplalka** [comment]
im using win7 64 bit os and vs2017 community with sql server 2008 and google chrome leatest version

**Comment by Deeplalka** [comment]
I'm too geting following error:
Running transformation: MsieJavaScriptEngine.JsRuntimeException: Object expected
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.InvokeScript[T](Func`1 func)
   at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.Evaluate(String expression)
   at MsieJavaScriptEngine.MsieJsEngine.Evaluate(String expression)
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TSTypeLister.SetupJsEngine() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude:line 251
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TSTypeLister.List() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude:line 262
   at Microsoft.VisualStudio.TextTemplating6AE85C52723D0B742902F85BA4179D6F69A23F91C2E41CE8EC4DFDFE28BC6D5FE7ECD399E629C4237D6B0B92E56A959F2DBD33AF9931AE4F51BD4246C582F322.GeneratedTextTransformation.TransformText() in E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\ServerTypings.tt:line 32		E:\WORK\Projects\MySerene\MySerene\MySerene.Web\Imports\ServerTypings\..\CodeGenerationHelpers.ttinclude	251	
 can any one gaide me for this please

im using win7 64 bit os and vs2017 community with sql server 2008 and google chrome leatest version
