### ISSUE TITLE
MultipleFileUploadEditor(AllowNonImage = true)

### ISSUE THREAD

**Issue by marcobisio** [volkanceylan/Serenity#718]
Dear @volkanceylan,
I have some trouble with the MultipleFileUploadEditor: it's working fine with images, text file, excel file etc. but if I try with a pdf or an executable file (about 3MB) then I get this:

![image](https://cloud.githubusercontent.com/assets/17425690/15475999/1d38cb00-210d-11e6-8fb2-efae38532218.png)

with the related exception in the BeforeSave() method:

    System.ArgumentOutOfRangeException was unhandled by user code
      HResult=-2146233086
      Message=Specified argument was out of the range of valid values.
    Parameter name: newFiles
      ParamName=newFiles
      Source=Serenity.Web
      StackTrace:
           at Serenity.Services.MultipleImageUploadBehavior.ParseAndValidate(String json, String key) in P:\Sandbox\Serene\Serenity\Serenity.Web\Upload\MultipleImageUploadBehavior.cs:line 71
           at Serenity.Services.MultipleImageUploadBehavior.OnBeforeSave(ISaveRequestHandler handler) in P:\Sandbox\Serene\Serenity\Serenity.Web\Upload\MultipleImageUploadBehavior.cs:line 93
           at Serenity.Services.SaveRequestHandler`3.BeforeSave() in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 47
           at eService.CSH.Repositories.TicketRepository.MySaveHandler.BeforeSave() in C:\SVN\Carestream\2016\eService\eService\eService.Web\Modules\CSH\Ticket\TicketRepository.cs:line 211
           at Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType) in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 283
           at eService.CSH.Repositories.TicketRepository.Update(IUnitOfWork uow, SaveRequest`1 request) in C:\SVN\Carestream\2016\eService\eService\eService.Web\Modules\CSH\Ticket\TicketRepository.cs:line 39
           at eService.CSH.Endpoints.TicketController.Update(IUnitOfWork uow, SaveRequest`1 request) in C:\SVN\Carestream\2016\eService\eService\eService.Web\Modules\CSH\Ticket\TicketEndpoint.cs:line 28
           at lambda_method(Closure , ControllerBase , Object[] )
           at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
           at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
           at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
           at Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) in P:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs:line 56
           at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
           at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
      InnerException: 

I'm doing something wrong?

Also I've seen that the plugin (jQuery File Upload Plugin 5.40.0) it's a bit outdated...it can be safely upgraded with the last version from here https://blueimp.github.io/jQuery-File-Upload/ or it requires also a server side patch?

Edit: forgot to add the stack trace

Thank you very much
Bye

**Comment by volkanceylan** [comment]
Search for Asp.Net httpruntime max request length

**Comment by volkanceylan** [comment]
http://stackoverflow.com/questions/288612/how-to-increase-the-max-upload-file-size-in-asp-net

**Comment by marcobisio** [comment]
Thank you very much for the hint @volkanceylan...
What about the plugin upgrade? Do you think that can be easily done or it will be a blood bath?

Bye

**Comment by volkanceylan** [comment]
I dont know if they changed something. Better try :)

**Comment by marcobisio** [comment]
Banzai mode = ON
I let you know :-)

Thank you very much (again)

**Comment by rgilsimoes** [comment]
Hi,
I'me having this issue on a FileList much like a NoteList.
I managed to create a "Add new File" dialog to a Entity like a "Add note". I'm able to upload the file but when I save the main Entity I get that error.
The file is small and is of type "image" I tried with AllowNonImage = true and with = false but got the same problem.

**Comment by marcobisio** [comment]
Which kind of error do you receive?

**Comment by rgilsimoes** [comment]
The error is:

The specified argument was outside the range of valid values.
Parameter Name: newFiles

```
   em Serenity.Services.MultipleImageUploadBehavior.ParseAndValidate(String json, String key) em P:\Sandbox\Serene\Serenity\Serenity.Web\Upload\MultipleImageUploadBehavior.cs:line 69
   em Serenity.Services.MultipleImageUploadBehavior.OnBeforeSave(ISaveRequestHandler handler) em P:\Sandbox\Serene\Serenity\Serenity.Web\Upload\MultipleImageUploadBehavior.cs:line 113
   em Serenity.Services.SaveRequestHandler`3.BeforeSave() em P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 47
   em Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType) em P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 287
   em SIINv2.Common.Repositories.AnexoRepository.Create(IUnitOfWork uow, SaveRequest`1 request) em C:\Work\LPCC\SIIN\SIINv2\SIINv2\SIINv2.Web\Modules\Common\Anexos\AnexoRepository.cs:line 18
   em SIINv2.Common.AnexoBehavior.SaveAnexo(IUnitOfWork uow, AnexoRow note, String entityType, Int64 entityId, Nullable`1 noteId) em C:\Work\LPCC\SIIN\SIINv2\SIINv2\SIINv2.Web\Modules\Common\Anexos\AnexoBehavior.cs:line 98
   em SIINv2.Common.AnexoBehavior.AnexoListSave(IUnitOfWork uow, String entityType, Int64 entityId, List`1 oldList, List`1 newList) em C:\Work\LPCC\SIIN\SIINv2\SIINv2\SIINv2.Web\Modules\Common\Anexos\AnexoBehavior.cs:line 119
   em SIINv2.Common.AnexoBehavior.OnAfterSave(ISaveRequestHandler handler) em C:\Work\LPCC\SIIN\SIINv2\SIINv2\SIINv2.Web\Modules\Common\Anexos\AnexoBehavior.cs:line 216
   em Serenity.Services.SaveRequestHandler`3.AfterSave() em P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 41
   em Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType) em P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 292
   em SIINv2.Entidades.Repositories.EntidadesRepository.Update(IUnitOfWork uow, SaveRequest`1 request) em C:\Work\LPCC\SIIN\SIINv2\SIINv2\SIINv2.Web\Modules\Entidades\Entidades\EntidadesRepository.cs:line 23
   em SIINv2.Entidades.Endpoints.EntidadesController.Update(IUnitOfWork uow, SaveRequest`1 request) em C:\Work\LPCC\SIIN\SIINv2\SIINv2\SIINv2.Web\Modules\Entidades\Entidades\EntidadesEndpoint.cs:line 28
   em lambda_method(Closure , ControllerBase , Object[] )
   em System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   em System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   em Serenity.Services.ServiceEndpoint.ServiceEndpointActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) em P:\Sandbox\Serene\Serenity\Serenity.Web\Mvc\ServiceEndpoint.cs:line 136
   em System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   em System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
```

**Comment by marcobisio** [comment]
Already tried with a different type of file? For example a .txt one?

**Comment by rgilsimoes** [comment]
Yes, just did.

**Comment by marcobisio** [comment]
I had no trouble at all on such editor, now I use a different one so I cannot test the same thing...if you try the same on an empty Serene project? There is such control here http://serenity.is/demo/Northwind/Product, just try the same file...
I know that some kind of file types are forbidden (.dll, .exe and so on), but I never had problems with images...
