### ISSUE TITLE
update Error with master-detail

### ISSUE THREAD

**Issue by Me-Kal** [volkanceylan/Serenity#987]
hi ,,
i have three table Survey , SurveyQuestions  and AnswerOptions  (master-detail)
i am adding Survey and it details (SurveyQuestions) and again from dialog detail (AnswerOptions) to SurveyQuestions.

it is working on insert but getting error on update , please note on update if i update all detail item one by one and  update master, it work . otherwise error

this is the exception in Repository

System.NotImplementedException was caught
  _HResult=-2147467263
  _message=The method or operation is not implemented.
  HResult=-2147467263
  IsTransient=false
  Message=The method or operation is not implemented.
  Source=Serenity.Data.Entity
  StackTrace:
       at Serenity.Data.RowListField`1.CompareValues(List`1 value1, List`1 value2) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\FieldTypes\RowListField.cs:line 16
       at Serenity.Data.CustomClassField`1.IndexCompare(Row row1, Row row2) in P:\Sandbox\Serene\Serenity\Serenity.Data.Entity\FieldTypes\CustomClassField.cs:line 58
       at Serenity.Services.MasterDetailRelationBehavior.DetailListSave(IUnitOfWork uow, Object masterId, IList oldList, IList newList) in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\IntegratedFeatures\MasterDetail\MasterDetailRelationBehavior.cs:line 270
       at Serenity.Services.MasterDetailRelationBehavior.OnAfterSave(ISaveRequestHandler handler) in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\IntegratedFeatures\MasterDetail\MasterDetailRelationBehavior.cs:line 349
       at Serenity.Services.SaveRequestHandler`3.AfterSave() in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 42
       at Serenity.Services.SaveRequestHandler`3.Process(IUnitOfWork unitOfWork, TSaveRequest request, SaveRequestType requestType) in P:\Sandbox\Serene\Serenity\Serenity.Services\RequestHandlers\Save\SaveRequestHandler.cs:line 288
       at AR2.Surveys.Repositories.SurveysRepository.Update(IUnitOfWork uow, SaveRequest`1 request) in c:\My Projects\AR2\AR2\AR2.Web\Modules\Surveys\Surveys\SurveysRepository.cs:line 25
  InnerException:

**Comment by Estrusco** [comment]
There seems to be an not implemented method. Search `throw new NotImplementedException();` in your solution

**Comment by volkanceylan** [comment]
Set CompareOldValues to false in your MasterDetailRelation.

**Comment by volkanceylan** [comment]
Sorry, CheckChangesOnUpdare

**Comment by Me-Kal** [comment]
CheckChangesOnUpdate=false  , Solved the isssue , thanks
